### PR TITLE
ci(jenkins): run edge tests in parallel

### PR DESCRIPTION
**Pull request by watson**

### CODE REVIEW

**Comment by watson** [comment]
Following up from #1277 - Turned out that the diff was much simpler than I had originally thought 😅

**Comment by watson** [comment]
@v1v 🤔 I guess it wasn't as simple as I thought... Jenkins is complaining

**Comment by v1v** [comment]
I was actually on the way to work on this in another PR, you were much faster :). Let me review it and I'll push the required changes if I'm able to make it work

**Comment by v1v** [comment]
Parallel stages before being running, aka waiting for a worker

image

Then in the BlueOcean view, you see something like 

image

Even though those branches have been already triggered:

image

And already assigned with some workers:

image

BlueOcean doesn't show those stages with parallel branches nicely though, let' see how it looks like when the build is done.

**Comment by watson** [comment]
No worries. As long as it looks ok in the end 👍 

Thanks for fixing this 😃

**Pull request merged**
