### PR TITLE
WIP: feat(mysql): support mysql2 module

### PR DESCRIPTION
**Pull request by danieljuhl**
Credits to @LewisJEllis elastic/apm-agent-nodejs#145 - I've simply created a new PR to get this merged.

### CODE REVIEW

**Comment by watson** [comment]
@danieljuhl Thanks a lot for taking a lead on this 😃 I can see that you added a `yarn.lock` file. This is the reason for the failing tests

**Comment by danieljuhl** [comment]
@watson that was not on purpose - thanks to CI. I'll remove tomorrow morning. Anything else?

**Comment by danieljuhl** [comment]
@watson I'm not familiar with tap, so I might take a little until I've managed to figure out exactly where the failure is happening and why... so I've marked the PR as WIP

**Comment by watson** [comment]
It seems to be a combination of a few equal assertions that fail and a test that never ends.

Here's an example of one of the equal assertion tests that fail:

```
# connection.query(query)
not ok 65 should be equal
  ---
    operator: equal
    expected: 1
    actual:   0
    at: Query.<anonymous> (/home/travis/build/elastic/apm-agent-nodejs/test/instrumentation/modules/mysql2/mysql.js:427:7)
```

This means that the test `connection.query(query)` had an equal assertion that failed in `test/instrumentation/modules/mysql2/mysql.js` on line 427. It expected the value to be `1` but it was `0`.

You also get a few `test exited without ending` errors, which means that either `t.end()` wasn't called or `t.plan()` wasn't fulfilled.

Let me know if you want help finding the culprits 😃

**Comment by watson** [comment]
@danieljuhl let me know if want to take another stab at this or if you want us to make the necessary changes to fix the tests so we can land this 😃

**Comment by danieljuhl** [comment]
@watson sorry, I've been busy lately. If you can fix it, it would be great - otherwise I'll give it another shot, but most likely not before start of May.

**Comment by danieljuhl** [comment]
closing in favor of #298

**Comment by watson** [comment]
Support for mysql2 have now been released in v1.7.0. Thanks so much for all your help landing this 😃

**Pull request closed without merging**
