### PR TITLE
test: split jenkins TAV tests up into smaller builds

### PR DESCRIPTION
**Pull request by watson**
Just trying things out for now...

### CODE REVIEW

**Comment by watson** [comment]
jenkins, run tav tests please

**Comment by watson** [comment]
jenkins, run tav tests please

**Comment by Qard** [comment]
LGTM, if we can get Jenkins slowness sorted.

**Comment by Qard** [comment]
jenkins, run tav tests please

**Comment by alvarolobato** [comment]
Will follow a different approach for this when we implement a new build pipeline

**Pull request closed without merging**
