### PR TITLE
ci(travis): disable npm cache

### PR DESCRIPTION
**Pull request by watson**
The npm cache used to be off by default on Travis, but since July 2019 they changed it to be on by default. This hides errors in our tests as updated to dependencies are no longer installed.

For details see:
https://docs.travis-ci.com/user/caching/#npm-cache

### CODE REVIEW

**Comment by Qard** [comment]
Looks like even 8.1 is broken by the `wait-on` dependency bump. 😞

**Comment by watson** [comment]
The minimum required version in the next major will be v8.6.0, so there's no need to worry about 8.1 anymore.

**Comment by Qard** [comment]
Should this be marked breaking-change then?

**Comment by watson** [comment]
(We should do this for Jenkins as well)

**Comment by watson** [comment]
> Should this be marked breaking-change then?

No, the test errors should preferably be fixed here first so we don't have a broken 2.x branch. Hopefully the wait-on fix is the only one.

**Comment by watson** [comment]
@Qard The fix with wait-on helped

**Comment by watson** [comment]
> (We should do this for Jenkins as well)

We're not caching `node_modules` on Jenkins, so all is good there

**Pull request merged**
