### PR TITLE
fix: set the transaction parent for an incoming HTTP/2 request (extra…

### PR DESCRIPTION
**Pull request by paulish**
With distributed tracing incoming http2 requests have no parent ids. This behavior can be observed using grpc/js module which is using http2 transport.

The change extracts parent ids and state from the request headers the similar way as it is done for http/1.

### Checklist

- [x] Implement code
- [ ] Add tests
- [x] Add CHANGELOG.asciidoc entry
- [x] Commit message follows [commit guidelines](https://github.com/elastic/apm-agent-nodejs/blob/main/CONTRIBUTING.md#commit-message-guidelines)

### CODE REVIEW

**Comment by paulish** [comment]
I have signed the contributor agreement

**Comment by trentm** [comment]
? All good?

**Comment by trentm** [comment]
Oh, I'm sorry I completely missed this the first time around!

It looks like we have this old issue about this: https://github.com/elastic/apm-agent-nodejs/issues/1830

**Comment by paulish** [comment]
No, not good. I had to sync my fork for own needs yesterday. I see no reason to wait a few months for integration of a small patch. I made the following changes:
```javascript
        const traceparent = headers.traceparent || headers['elastic-apm-traceparent']
        const tracestate = headers.tracestate
        const trans = agent.startTransaction(null, null, {
          childOf: traceparent,
          tracestate: tracestate
        })
```
IOW, just fulfilled the `childOf` and `tracestate` properties.

**Comment by trentm** [comment]
@paulish I apologize for that. I just missed this PR. If you want to revive this PR, I'll merge it. If not (I understand), I'll open a new PR doing the equivalent in the next couple of days.

**Comment by paulish** [comment]
@trentm, Github does not allow me to create a merge request now (after I synced my branch with upstream). At the same time I see the difference in my fork of http2.js.  I can delete my fork and create it again to make a new merge request if you wish.

**Comment by trentm** [comment]
> I can delete my fork and create it again to make a new merge request if you wish.

Yes, please. (But I'm aware you had a bad experience, so if you just want me to do all PR work I would understand.)

**Comment by paulish** [comment]
@trentm done here: https://github.com/elastic/apm-agent-nodejs/pull/3451

**Pull request closed without merging**
