### PR TITLE
feat(express-queue): retain continuity through express-queue

### LINKED ISSUE #373: Add support for express-queue module
Related issue: elastic/apm-agent-nodejs#367

The [express-queue](https://github.com/alykoshin/express-queue) module adds a user-land callback queue and therefore breaks the async context propagation.

Steps to reproduce:

1. Start the following server
    ```js
    const agent = require('./').start({
      serviceName: 'test',
      captureExceptions: false
    })
    const assert = require('assert')
    
    // hijack the request to the APM Server to validate the payload
    agent._httpClient.request = function (endpoint, headers, data, cb) {
      data.transactions.forEach(function (trans) {
        assert.equal(trans.result, 'HTTP 2xx')
      })
    }
    
    const express = require('express')
    const queue = require('express-queue')
    const app = express()
    
    app.use(queue({activeLimit: 2, queuedLimit: -1}))
    
    app.get('/', function (req, res) {
      setImmediate(function () {
        res.end()
      })
    })
    
    app.listen(3000)
    ```
1. Send a lot of simultainious requests to the server using autocannon:
    ```sh
    autocannon localhost:3000
    ```

### Todo

- [ ] Patch the module
- [ ] Add tests
- [ ] Document it in the [Continuity section](https://github.com/elastic/apm-agent-nodejs/blob/master/docs/compatibility.asciidoc#continuity) in compatibility.asciidoc

### PR DESCRIPTION
**Pull request by Qard**
This fixes the continuity issue with express-queue.

Fixes #373

### Checklist

- [x] Implement code
- [x] Add tests
- [x] Update documentation

### CODE REVIEW

**Comment by watson** [comment]
Seems like the express-queue v0.0.10 and below isn't supported by this patch. If it's gonna be complicated to add support for it, I say we just don't support older versions and call it a day.

**Comment by Qard** [comment]
Strange. I did a TAV test locally, before pushing the code up, and had zero failures. 🤔

**Comment by Qard** [comment]
Oh...I did it on v4, which exits early. 😅

**Comment by Qard** [comment]
@watson It looks like pre-0.0.11 will be somewhat more difficult to patch, but is functionally identical, from the user perspective. I've restricted this PR to only support 0.0.11+. I'd recommend not bothering with earlier versions unless someone asks for it.

**Comment by watson** [comment]
jenkins test this please

**Comment by watson** [comment]
jenkins test this please

**Comment by watson** [comment]
jenkins test this please

**Comment by watson** [comment]
Finally Jenkins is passing (flimsy tests). But now I have to figure out why codecov is failing. So far I'm getting a 401 when trying to access the codecov site for some reason.

**Comment by Qard** [comment]
Works for me. Probably just a minor blip in uptime for codecov.

**Comment by watson** [comment]
@Qard I would to some degree consider this a bug fix rather than a new feature. It's of course not black and white, and I can probably go either way. What do you think?

**Comment by Qard** [comment]
I can see a case for either.

On one hand, it doesn't really add a "feature" from a user-facing perspective. On the other hand, calling it a bug fix could be interpreted as a statement that _every_ occurrence of continuity-loss in userland modules should be accounted for, which is unrealistic. Considering support for continuity through a given module to be a feature might make more sense.

I'm good either way though. What do you think?

**Comment by watson** [comment]
Yeah, it's tricky - up there with cache invalidation and naming things 😉

A user using `express-queue` without this patch would see what they would characterize as bugs. So from their point of view - without knowing what we know - this is a "bug fix".

But I agree we can't take the responsibility for these sort of errors as we have no control over user land code - and we might even have situations where we simply say that we can't add support for a given module. I'm personally not afraid that people would start assuming stuff like this is our fault even if we called it a `fix` in this case.

I'll go ahead and rename the commit to say `fix` when merging #yolo

**Pull request merged**
