### PR TITLE
chore: update CI for node v18.0.0

### PR DESCRIPTION
**Pull request by trentm**
Closes: #2650

### Checklist

- [x] Implement code
- [x] Add CHANGELOG.asciidoc entry

### CODE REVIEW

**Comment by trentm** [comment]
Jenkins CI tests failed on:

```
[2022-04-20T17:29:24.572Z] + .ci/scripts/test.sh -b release -t  18
[2022-04-20T17:29:24.572Z] Running Agent tests with node v18 (BUILD_TYPE=release, FORCE=false)
...
[2022-04-20T17:29:24.572Z] .ci/scripts/test.sh:226: main(): DOCKER_COMPOSE_FILE=docker-compose-all.yml
...
[2022-04-20T17:29:24.572Z] .ci/scripts/test.sh:232: main(): NODE_VERSION=18
...
[2022-04-20T17:29:24.572Z] .ci/scripts/test.sh:232: main(): docker-compose --no-ansi --log-level ERROR -f .ci/docker/docker-compose-all.yml build
[2022-04-20T17:29:26.497Z] .ci/scripts/test.sh:244: main(): '[' 1 -gt 0 ']'
[2022-04-20T17:29:26.497Z] .ci/scripts/test.sh:245: main(): echo 'Docker compose failed, see the below log output'
[2022-04-20T17:29:26.497Z] Docker compose failed, see the below log output
```

Because (as with earlier major first releases), there isn't yet a published "node:18" to Docker Hub: https://hub.docker.com/_/node

[Last time](https://github.com/elastic/apm-agent-nodejs/pull/2380) this took a day or three, IIRC.

- https://github.com/nodejs/docker-node/pull/1697 is done
- I believe next is https://github.com/docker-library/official-images/pull/12266 that will provide "node:18" docker images.

Note that the GH Actions test of node 18 worked.

**Comment by trentm** [comment]
> Note that the GH Actions test of node 18 worked.

I would be in favour of our Jenkins CI tests *not* depending on `node:*` docker images for testing that version of node and instead doing what GH Action's "setup-node" action is doing:

```
Acquiring 18.0.0 - x64 from https://github.com/actions/node-versions/releases/download/18.0.0-2193993879/node-18.0.0-linux-x64.tar.gz
Extracting ...
/usr/bin/tar xz --strip 1 --warning=no-unknown-keyword -C /home/runner/work/_temp/37ea3dd2-f17e-4539-86e6-c783a5afbef2 -f /home/runner/work/_temp/7314e7fa-5e6d-4642-a566-8bbf67743b74
```

The build and publish of "node:*" images to Docker Hub is a separate process to the Node core team doing a release. If the former fails or is delayed a long time... we won't be testing with the latest release of node.  Anyway... for another issue, unless the delay in getting node:18 drags on.

**Comment by trentm** [comment]
run module tests for ALL

**Review by astorm — APPROVED** [review]

**Pull request merged**
