### PR TITLE
fix(package): bump all dependencies

### PR DESCRIPTION
**Pull request by watson**

### CODE REVIEW

**Comment by Qard** [comment]
Looks like there are syntax errors on 8.0 and earlier.

**Comment by watson** [comment]
Accidently reintroduced the old wait-on bug... should be fixed now

**Comment by watson** [comment]
I'll go ahead and merge this one as I foresee a merge conflict with #1355 - I hope you don't mind 🙂

**Comment by Qard** [comment]
Yep, that's fine. As long as the tests pass dependency updates should be largely uncontroversial.

**Pull request merged**
