### PR TITLE
Fix #1770 support for proxies in destination context

### LINKED ISSUE #1770: Add support for proxies in destination context
If a proxy is used, the destination context will not be set on outgoing http spans because the URL cannot be successfully extracted from the request. For details see #1769.

### PR DESCRIPTION
**Pull request by ebuildy**
Fix #1770 issue:

If a proxy is used, the destination context will not be set on outgoing http spans because the URL cannot be successfully extracted from the request.

Copy/paste from https://github.com/Qard/http-request-to-url/commit/7406c37baad7625c1bdfa17c1b62b821f55fbe03

### Checklist

- [x] Implement code
- [ ] Add tests
- [x] Update TypeScript typings
- [x] Update documentation
- [ ] Add CHANGELOG.asciidoc entry
- [x] Commit message follows [commit guidelines](https://github.com/elastic/apm-agent-nodejs/blob/master/CONTRIBUTING.md#commit-message-guidelines)

### CODE REVIEW

**Comment by trentm** [comment]
@ebuildy Thanks.

The best original discussion of this is here: https://github.com/Qard/http-request-to-url/issues/1
There is also a test case example there. Can we take that and add to the test suite here?

**Comment by trentm** [comment]
jenkins run the tests

**Comment by trentm** [comment]
I'm not clear on the history of commits here. Is this proxy functionality something we missed in #2039 where the 'http-request-to-url' dep was removed?

**Comment by ebuildy** [comment]
There is an old bug in case we use HTTP proxy to send query, the URL from ``request.path`` == proxied URL (the URL we want to report in APM). The problem is this throw error all the time (see https://github.com/elastic/apm-agent-nodejs/blob/a2c47771b66a7fe4f46122094241bf99287835ce/lib/instrumentation/http-shared.js#L224 ) and fill logs (whereas the URL is valid).

**Comment by astorm** [comment]
jenkins run the tests please

**Comment by astorm** [comment]
> There is an old bug in case we use HTTP proxy to send query, the URL from request.path == proxied URL (the URL we want to report in APM). The problem is this throw error all the time (see https://github.com/elastic/apm-agent-nodejs/blob/a2c47771b66a7fe4f46122094241bf99287835ce/lib/instrumentation/http-shared.js#L224  ) and fill logs (whereas the URL is valid).

Additional Context: We had hoped/assumed that removing the dependency on `http-request-to-url` would fix this behavior.  However, it did not. FWIW I managed to cobble together a proxy server that reproduced the behavior we're trying to fix (https://github.com/elastic/apm-agent-nodejs/issues/1770#issuecomment-867833122) so we should be able to validate it this time.

**Comment by ebuildy** [comment]
Wonderful! 

It looks like a bug from nodeJS it-self actually, there is no way to guess if a https://github.com/nodejs/node/blob/master/lib/_http_client.js ClientRequest is using a proxy or not.

**Comment by astorm** [comment]
@elasticmachine, run elasticsearch-ci/docs

**Comment by astorm** [comment]
It looks like our CI is happy with things.  Per @trentm's comments above

> Can we take that and add to the test suite here?

I've written up a test that captures the intent of this fix, based on the `http-request-to-url` test
https://gist.github.com/astorm/ff0211e076d670d3c41e8fe0169f8532

@ebuildy -- would you be able to 

1. Add the test at the above gist to your PR
2. Add an entry to the CHANGELOG.asciidoc mentioning this bug fix?

With those in place we should be able to merge.

**Comment by astorm** [comment]
jenkins run the tests

**Comment by astorm** [comment]
jenkins run the tests please

**Comment by astorm** [comment]
@elasticmachine, run elasticsearch-ci/docs

**Comment by astorm** [comment]
@ebuildy Apologies -- it looks like there's a timing issue in the test I handed you (only pops up in Node 8.6).  I made a PR to your branch to fix that.  https://github.com/ebuildy/apm-agent-nodejs/pull/1/files

**Comment by ebuildy** [comment]
Ok got it! thanks you. (Sorry for the delay, I am in France ....)

**Comment by astorm** [comment]
@ebuildy No rush intended or asked for :)  

Also -- PR to fix the above linting errors: https://github.com/ebuildy/apm-agent-nodejs/pull/2

**Comment by ebuildy** [comment]
sure! just saying that because I answer always a day after. Thanks you for the fix

**Comment by astorm** [comment]
jenkins run the tests please

**Comment by astorm** [comment]
@elasticmachine, run elasticsearch-ci/docs

**Comment by astorm** [comment]
jenkins run the tests please

**Comment by astorm** [comment]
@elasticmachine, run elasticsearch-ci/docs

**Review by astorm — APPROVED** [review]
👍 does the thing, approving and merging

**Pull request merged**
