### PR TITLE
docs: header name with sampled flag

### PR DESCRIPTION
**Pull request by sefiros1**
Fixed header name with sampled flag in docs.

### Checklist

- [x] Update documentation
- [x] Commit message follows [commit guidelines](https://github.com/elastic/apm-agent-nodejs/blob/main/CONTRIBUTING.md#commit-message-guidelines)

### CODE REVIEW

**Comment by trentm** [comment]
@sefiros1 Though it is silly for this small change, are you able to sign our [contributor agreement](https://www.elastic.co/contributor-agreement)?

**Review by trentm — APPROVED** [review]

**Comment by trentm** [comment]
@elasticmachine, run elasticsearch-ci/docs

**Comment by sefiros1** [comment]
@trentm I signed right after I created the PR. Is there any way to restart the pipeline check?

**Comment by trentm** [comment]
@sefiros1 Looks like the CLA-check went through. I didn't have to restart it, so I guess it was just delayed.  Don't be sorry at all!

**Comment by trentm** [comment]
@sefiros1 Thanks!

**Comment by trentm** [comment]
Ah... this was against the '3.x' branch. This should have gone against the 'main' branch. My bad for not noticing this earlier. I've cherry-picked it into main.

**Pull request merged**
