### PR TITLE
tests: fix failing restify tests with latest node v18.0.0 nightly

### PR DESCRIPTION
**Pull request by trentm**
Restify currently does not work with the latest v18.0.0 nightly.
See https://github.com/restify/node-restify/issues/1888

"Edge" nightly tests recently started failing on this. E.g.:
https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-nodejs%2Fapm-agent-nodejs-mbp/detail/master/1178/pipeline/6508

```
[2021-11-15T07:16:33.458Z] node_tests_1     | # disableInstrumentations
[2021-11-15T07:16:33.458Z] node_tests_1     | # individual modules -> @elastic/elasticsearch
[2021-11-15T07:16:43.490Z] node_tests_1     | /app/node_modules/restify/lib/request.js:848
[2021-11-15T07:16:43.490Z] node_tests_1     |     Request.prototype.closed = function closed() {
[2021-11-15T07:16:43.490Z] node_tests_1     |                              ^
[2021-11-15T07:16:43.490Z] node_tests_1     | 
[2021-11-15T07:16:43.490Z] node_tests_1     | TypeError: Cannot set property closed of #<Readable> which has only a getter
[2021-11-15T07:16:43.490Z] node_tests_1     |     at patch (/app/node_modules/restify/lib/request.js:848:30)
[2021-11-15T07:16:43.490Z] node_tests_1     |     at Object.<anonymous> (/app/node_modules/restify/lib/server.js:33:1)
[2021-11-15T07:16:43.490Z] node_tests_1     |     at Module._compile (node:internal/modules/cjs/loader:1097:14)
[2021-11-15T07:16:43.490Z] node_tests_1     |     at Module.replacementCompile (/app/node_modules/append-transform/index.js:60:13)
[2021-11-15T07:16:43.491Z] node_tests_1     |     at Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
[2021-11-15T07:16:43.491Z] node_tests_1     |     at Object.<anonymous> (/app/node_modules/append-transform/index.js:64:4)
[2021-11-15T07:16:43.491Z] node_tests_1     |     at Module.load (node:internal/modules/cjs/loader:975:32)
[2021-11-15T07:16:43.491Z] node_tests_1     |     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
[2021-11-15T07:16:43.491Z] node_tests_1     |     at Module.require (node:internal/modules/cjs/loader:999:19)
[2021-11-15T07:16:43.491Z] node_tests_1     |     at Module.Hook._require.Module.require (/app/node_modules/require-in-the-middle/index.js:80:39)
[2021-11-15T07:16:43.491Z] node_tests_1     |     at require (node:internal/modules/cjs/helpers:102:18)
[2021-11-15T07:16:43.491Z] node_tests_1     |     at Object.<anonymous> (/app/node_modules/restify/lib/index.js:10:14)
[2021-11-15T07:16:43.491Z] node_tests_1     |     at Module._compile (node:internal/modules/cjs/loader:1097:14)
[2021-11-15T07:16:43.491Z] node_tests_1     |     at Module.replacementCompile (/app/node_modules/append-transform/index.js:60:13)
[2021-11-15T07:16:43.491Z] node_tests_1     |     at Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
[2021-11-15T07:16:43.491Z] node_tests_1     |     at Object.<anonymous> (/app/node_modules/append-transform/index.js:64:4)
[2021-11-15T07:16:43.491Z] node_tests_1     |     at Module.load (node:internal/modules/cjs/loader:975:32
[2021-11-15T07:16:43.491Z] node_tests_1     |     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
[2021-11-15T07:16:43.491Z] node_tests_1     |     at Module.require (node:internal/modules/cjs/loader:999:19)
[2021-11-15T07:16:43.491Z] node_tests_1     |     at Module.Hook._require.Module.require (/app/node_modules/require-in-the-middle/index.js:80:39)
[2021-11-15T07:16:43.491Z] node_tests_1     |     at require (node:internal/modules/cjs/helpers:102:18)
[2021-11-15T07:16:43.491Z] node_tests_1     |     at Test.<anonymous> (/app/test/config.test.js:877:9)
[2021-11-15T07:16:43.491Z] node_tests_1     |     at Test.bound [as _cb] (/app/node_modules/tape/lib/test.js:96:32)
[2021-11-15T07:16:43.491Z] node_tests_1     |     at Test.run (/app/node_modules/tape/lib/test.js:114:31)
[2021-11-15T07:16:43.491Z] node_tests_1     |     at Test.bound [as run] (/app/node_modules/tape/lib/test.js:96:32)
[2021-11-15T07:16:43.491Z] node_tests_1     |     at Test._end (/app/node_modules/tape/lib/test.js:217:11)
[2021-11-15T07:16:43.491Z] node_tests_1     |     at Test.bound [as _end] (/app/node_modules/tape/lib/test.js:96:32)
[2021-11-15T07:16:43.491Z] node_tests_1     |     at Test.end (/app/node_modules/tape/lib/test.js:196:10)
[2021-11-15T07:16:43.491Z] node_tests_1     |     at Test.bound [as end] (/app/node_modules/tape/lib/test.js:96:32)
[2021-11-15T07:16:43.491Z] node_tests_1     |     at Test.<anonymous> (/app/test/config.test.js:899:5)
[2021-11-15T07:16:43.491Z] node_tests_1     |     at Test.bound [as _cb] (/app/node_modules/tape/lib/test.js:96:32)
[2021-11-15T07:16:43.491Z] node_tests_1     |     at Test.run (/app/node_modules/tape/lib/test.js:114:31)
[2021-11-15T07:16:43.491Z] node_tests_1     |     at Test.bound [as run] (/app/node_modules/tape/lib/test.js:96:32)
[2021-11-15T07:16:43.491Z] node_tests_1     |     at Immediate.next (/app/node_modules/tape/lib/results.js:88:19)
[2021-11-15T07:16:43.491Z] node_tests_1     |     at processImmediate (node:internal/timers:464:21)
[2021-11-15T07:16:43.491Z] node_tests_1     | 
[2021-11-15T07:16:43.491Z] node_tests_1     | Node.js v18.0.0-nightly20211114cf56abe6bb
```

### Checklist

- [x] Implement code
- [x] Commit message follows [commit guidelines](https://github.com/elastic/apm-agent-nodejs/blob/master/CONTRIBUTING.md#commit-message-guidelines)

### CODE REVIEW

**Comment by trentm** [comment]
https://apm-ci.elastic.co/job/apm-agent-nodejs/job/apm-agent-nodejs-mbp/job/PR-2447/2/ is a run of the edge tests to see if this fixes it.

**Comment by trentm** [comment]
> https://apm-ci.elastic.co/job/apm-agent-nodejs/job/apm-agent-nodejs-mbp/job/PR-2447/2/ is a run of the edge tests to see if this fixes it.

This passed.

**Review by astorm — COMMENTED** [review]
Question -- if I'm reading this correctly it looks like we're skipping the restify tests if the node version is greater than 17, full stop. 

Is there anything we can do to skip only the nighties, or will it be on us to remember to reenable these tests at some point?

**Comment by trentm** [comment]
> will it be on us to remember to reenable these tests at some point?

This. Do you have a suggestion on how to not forget this? I will get a personal notification from the restify issue above if/when that is resolved. That was going to be my (somewhat poor) trigger to update our tests here.

**Review by astorm — APPROVED** [review]

**Comment by astorm** [comment]
> This. Do you have a suggestion on how to not forget this? I will get a personal notification from the restify issue above if/when that is resolved. That was going to be my (somewhat poor) trigger to update our tests here.

Works for me, as I don't have any silver bullets -- best I can come up with is out own issue and tagging it as a "necessary for Node 18" or using a date based guard clauses in addition to the semver checks.

**Pull request merged**
