### PR TITLE
feat(express-graphql): add support for v0.9

### PR DESCRIPTION
**Pull request by watson**

### CODE REVIEW

**Comment by watson** [comment]
jenkins run the module tests for express-graphql

**Comment by Qard** [comment]
Looks like it needs to bail out on Node.js 6 due to new syntax.

**Comment by watson** [comment]
I'm having issues with Travis being super slow and timing out. I've restarted some of the tests 3 times now and they still end up running into the 2h timelimit. But they are not related to this PR, so we should just ignore them. This PR is therefore ready to merge if approved 👍

**Comment by Qard** [comment]
I see the timeout, but I _also_ see a legit failure here: https://travis-ci.org/elastic/apm-agent-nodejs/jobs/568246245#L4403

**Comment by watson** [comment]
Yeah npm on Travis is behaving weirdly I think. I've been getting those errors all day yesteday. If you re-run the builds a few times you get different errors or if you're lucky they go away

**Comment by watson** [comment]
@Qard I re-ran the tests after Travis got over the problems and now it's all green. So just waiting for your review :)

**Pull request merged**
