### PR TITLE
[docs] Add information for explicitly calling `apm.start()`

### PR DESCRIPTION
**Pull request by mesaugat**
- [x] Update documentation

For people who navigate to the ES Modules page directly, it is easy to miss that the agent will start automatically with a top level `import elastic-apm-node/start`. This is something I faced myself while integrating the agent.

I've emphasized the section where it mentions that the configuration object cannot be passed. Also, added a line that mentions how to explicitly start the agent.

### CODE REVIEW

**Comment by watson** [comment]
Thanks for taking the time to make a contribution to the project.

Unfortunately, your commit is also changing the wrapping of some of the lines in the markdown file, which makes it hard to review. This is probably your editor that's configured to wrap lines automatically upon save. Could I get you to update the PR so it only changes the lines that you intended to change?

Tip: When you stage changes to be committed, you can use `git add -p` to be prompted for each change so you don't accidentally add changes you didn't mean to 🙂

**Comment by mesaugat** [comment]
@watson The editor did not change the wrapped lines, I did it myself because I found the doc to be inconsistently formatted. Anyways, I've only included the changes that I've made.

**Comment by Qard** [comment]
LGTM other than commit titles failing the linter.

@bmorelli25 Feel free to merge, if it looks good to you, just make sure to use squash and merge to rename the commit to something that follows the commit title guidelines. :)

**Comment by Qard** [comment]
@bmorelli25 What's the status of this? Do you want to make a copy of this PR so we can get this landed and closed?

**Comment by Qard** [comment]
Closed by #1258.

**Pull request closed without merging**
