### PR TITLE
feat(config): default serviceVersion to package version

### LINKED ISSUE #1234: Use package.json version as default serviceVersion
We currently use the `name` field in the `package.json` file as the default for the `serviceName` option. We should probably do the same with mapping the `version` field to `serviceVersion`.

### PR DESCRIPTION
**Pull request by yuxizhe**
fix #1234
### Checklist

- [x] Implement code
- [x] Add tests
- [x] Update documentation

### CODE REVIEW

**Comment by Qard** [comment]
jenkins test this please

**Comment by Qard** [comment]
Oh, looks like you will also need to update [this line](https://github.com/elastic/apm-agent-nodejs/blob/master/test/config.js#L30) to get the `version` field from the module `package.json` and put it in the third array position. Current `SERVICE_NAME` hardcodes this to match the package name, so maybe make that dynamically loaded from the `package.json` too while you're in there. 🤔

**Comment by Qard** [comment]
jenkins run the tests

**Comment by yuxizhe** [comment]
> Oh, looks like you will also need to update [this line](https://github.com/elastic/apm-agent-nodejs/blob/master/test/config.js#L30) to get the `version` field from the module `package.json` and put it in the third array position. Currently `SERVICE_NAME` hardcodes this to match the package name, so maybe make that dynamically loaded from the `package.json` too while you're in there. 🤔

oh I see, fixed :）

**Comment by Qard** [comment]
jenkins run the tests please

**Comment by Qard** [comment]
run tests

**Comment by yuxizhe** [comment]
SERVICE_NAME also loaded from package.json now.

**Comment by Qard** [comment]
jenkins run the tests

**Comment by Qard** [comment]
jenkins run the tests please

**Comment by Qard** [comment]
Test failures are unrelated. I've verified this works locally, so I will land as-is and investigate the failures separately.

**Pull request merged**
