### PR TITLE
feat(pg): add support for pg v8.x

### PR DESCRIPTION
**Pull request by watson**

### CODE REVIEW

**Comment by watson** [comment]
jenkins run the tests please

**Comment by JCMais** [comment]
@watson just fyi, pg now uses defineProperty as can be seen here: https://github.com/brianc/node-postgres/blob/2ef55503738eb2cbb6326744381a92c0bc0439ab/packages/pg/lib/index.js#L39-L62

Probably a good idea to also use the same here, it could be implemented like this: https://github.com/elastic/apm-agent-nodejs/pull/1735/files#diff-874721d67e97b9e5e232fda1af5d07ed

**Comment by watson** [comment]
@JCMais sorry that I missed that you already had a PR open for this. I'll be happy to implement your changes if your open a new PR 😃

**Comment by JCMais** [comment]
Hey @watson, unfortunately, I don't have time to work on a new PR, feel free to reuse the code, no need for attribution.

**Pull request merged**
