### PR TITLE
test(graphql): test transaction have name for sub-queries

### PR DESCRIPTION
**Pull request by watson**

### CODE REVIEW

**Comment by mikker** [comment]
Thanks for adding a test. I can't find where the expected title should be?

**Comment by watson** [comment]
@mikker it's down in the `done` function below the new test.

Seems like the tests are currently broken though... but unrelated to the PR 🤷‍♂

**Comment by mikker** [comment]
Oh, so just `books` from here https://github.com/elastic/apm-agent-nodejs/pull/1616/files#diff-214a9bd0d750ceb63f5e377e530443b9R199

**Comment by watson** [comment]
jenkins run the module tests for apollo-server-express

**Pull request merged**
