### PR TITLE
docs: add tip/warning to labels

### PR DESCRIPTION
**Pull request by bmorelli25**
Implements: elastic/apm#77
~Blocked by: elastic/apm-server#2129~

### CODE REVIEW

**Comment by bmorelli25** [comment]
APM Server PR has been merged - no longer blocked.

Retest this please

**Comment by bmorelli25** [comment]
Backported the APM Server documentation to 7.0... links should work now 🤞Retest this please.

**Comment by bmorelli25** [comment]
Hmmm let's try one more time.

retest this please

**Comment by bmorelli25** [comment]
Yay! Finally a green docs build. @qard is the failing appveyor test ok?

**Comment by Qard** [comment]
Yep. That's unrelated. Probably an intermittent failure--we get a lot of those with AppVeyor.

**Pull request merged**
