### PR TITLE
3.25.0

### PR DESCRIPTION
**Pull request by trentm**
We have some improvements to release and this will allow us to get a fix for a broken link in the "current" published version of the docs (see https://github.com/elastic/apm-agent-nodejs/pull/2465#issuecomment-977254161).

### CODE REVIEW

**Review by astorm — APPROVED** [review]
approved pending CI pass

**Comment by trentm** [comment]
New test failure:

```
running (cwd: ./): node --unhandled-rejections=strict test/instrumentation/modules/@elastic/elasticsearch-canary.test.js
...
not ok 137 elasticsearch span has correct .context.db
  ---
    operator: deepEqual
    expected: |-
      { type: 'elasticsearch', statement: '{"query":{"match":{"request":"bar"}},"size":2,"sort":"myField:asc"}' }
    actual: |-
      { type: 'elasticsearch', statement: 'sort=myField%3Aasc\n\n{"query":{"match":{"request":"bar"}},"size":2}' }
    at: <anonymous> (/home/runner/work/apm-agent-nodejs/apm-agent-nodejs/test/instrumentation/modules/@elastic/elasticsearch.test.js:756:9)
    stack: |-
      Error: elasticsearch span has correct .context.db
          at Test.assert [as _assert] (/home/runner/work/apm-agent-nodejs/apm-agent-nodejs/node_modules/tape/lib/test.js:311:54)
          at Test.bound [as _assert] (/home/runner/work/apm-agent-nodejs/apm-agent-nodejs/node_modules/tape/lib/test.js:96:32)
          at Test.tapeDeepEqual (/home/runner/work/apm-agent-nodejs/apm-agent-nodejs/node_modules/tape/lib/test.js:552:10)
          at Test.bound [as deepEqual] (/home/runner/work/apm-agent-nodejs/apm-agent-nodejs/node_modules/tape/lib/test.js:96:32)
          at /home/runner/work/apm-agent-nodejs/apm-agent-nodejs/test/instrumentation/modules/@elastic/elasticsearch.test.js:756:9
          at Timeout._onTimeout (/home/runner/work/apm-agent-nodejs/apm-agent-nodejs/test/_mock_http_client.js:65:7)
          at listOnTimeout (internal/timers.js:549:17)
          at processTimers (internal/timers.js:492:7)
  ...
  ```

This changed behaviour between `@elastic/elasticsearch-canary@8.0.0-canary.35` and `@elastic/elasticsearch-canary@8.0.0-canary.37`. Fun fun.

**Comment by trentm** [comment]
I manually started TAV and edge tests for this branch: https://apm-ci.elastic.co/job/apm-agent-nodejs/job/apm-agent-nodejs-mbp/job/PR-2466/3/

**Comment by trentm** [comment]
elastic-apm-node@3.25.0 published
v3.25.0 tagged

**Pull request merged**
