### PR TITLE
test(ci): add codecov.yml for status indicators

### LINKED ISSUE #113: Switch codecov to report via PR checks instead of a comment
Today codecov will post a pretty length comment on PR's. Takes up a lot of real-estate 😞 

Instead we should do what the Python agent is doing and just have it change the status of the PR:

image

See the [codecov.yml](https://github.com/elastic/apm-agent-python/blob/master/codecov.yml) file from the Python agent for inspiration.

### PR DESCRIPTION
**Pull request by Qard**
Fixes #113

### CODE REVIEW

**Comment by watson** [comment]
I would have expected this PR it self to then have the codecov checks, but maybe it only works properly after it have been checked into master?

image

@beniwohli what's your experience?

**Comment by beniwohli** [comment]
@watson can't remember tbh :(

**Comment by watson** [comment]
We only live once 😎  Let's try and merge it and see if it starts working after it's in master.

**Comment by Qard** [comment]
fixed

**Pull request merged**
