### PR TITLE
Add metrics for external memory

### PR DESCRIPTION
**Pull request by SimonSimCity**
This ticket adds some metrics missing of #309.

I've added the metrics `nodejs.memory.external.bytes` and `nodejs.memory.arrayBuffers.bytes` (available from node 13.x).

All memory related data is now collected using `process.memoryUsage()` which has a better documentation than the internal v8 methods: https://nodejs.org/docs/latest/api/process.html#process_process_memoryusage

### Checklist

- [x] Implement code
- [x] Add tests
- [x] Update documentation
- [x] Commit message follows [commit guidelines](https://github.com/elastic/apm-agent-nodejs/blob/master/CONTRIBUTING.md#commit-message-guidelines)

### CODE REVIEW

**Comment by bmorelli25** [comment]
@elasticmachine, run elasticsearch-ci/docs

**Comment by SimonSimCity** [comment]
Anything postponing this? I'd like to have it in soon to monitor long-term memory development of the C-libraries of my node-application.

**Comment by lreuven** [comment]
Hi,
Thanks for the contribution,
@vigneshshanmugam can you have a look when you have the time?

**Comment by bmorelli25** [comment]
@elasticmachine, run elasticsearch-ci/docs

**Comment by axw** [comment]
> One question on the APM Server part. Do we control the custom metrics in any way or we can keep adding new ones whenever we find the use-case for it?

@vigneshshanmugam as long as there's a clear use-case for it, it's fine to add new metrics. It's best to align across agents where we can, but these ones are pretty Node.js-specific so no worries there.

**Pull request merged**
