### PR TITLE
ci(jenkins): enable tests for nighlty and rc versions

### PR DESCRIPTION
**Pull request by v1v**
Fixes https://github.com/elastic/apm-agent-nodejs/issues/1135

## Highlights
- Run tests for nightly and RC versions.
- Run only for the master branch and when it's triggered with the cron timer.
- Node versions are defined in `.ci/.jenkins_edge_nodejs.yml`
- It won't run TAV but normal tests. Therefore this PR doesn't support TAV for cutting edge versions, just to be sure if it's required in the future the implementation might require to deprecate the `.ci/docker/node-container/Dockerfile` docker image and use `.ci/docker/node-edge-container/Dockerfile` in the `.ci/docker/docker-compose-all.yml` docker compose file.
- New GitHub checks
image

image
- You can force manually if you fill the build form with `Run_As_Master_Branch` and `test_edge_ci` as stated below

image

## Pipeline UI

image

## Tasks
- [x] Adapt the docker containers to use nightly/RC versions

## Tests
- Run the nightly edge version 12
```
export NVM_NODEJS_ORG_MIRROR="https://nodejs.org/download/nightly/"
.ci/scripts/test.sh 12 '' true
...
node_tests_1     | + node --version
node_tests_1     | v12.0.0-nightly20190423859421188b
node_tests_1     | + npm --version
node_tests_1     | 6.10.1
...
node_tests_1     | + nyc report --reporter=lcov
docker_node_tests_1 exited with code 0
Aborting on container exit...
```

- Run the RC edge version 12
```
export NVM_NODEJS_ORG_MIRROR="https://nodejs.org/download/rc/"
.ci/scripts/test.sh 12 '' true
...
node_tests_1     | + node --version
node_tests_1     | v12.0.0-rc.3
node_tests_1     | + npm --version
node_tests_1     | 6.10.1
...
node_tests_1     | + nyc report --reporter=lcov
docker_node_tests_1 exited with code 0
Aborting on container exit...
```

- Run the RC edge version 12 with No async hooks
```
export ELASTIC_APM_ASYNC_HOOKS="false"
export NVM_NODEJS_ORG_MIRROR="https://nodejs.org/download/rc/"
.ci/scripts/test.sh 12 '' true
+ DOCKER_FOLDER=.ci/docker
+ NODE_VERSION=12
+ TAV_VERSIONS=
+ IS_EDGE=true
+ case ${TAV_VERSIONS} in
+ DOCKER_COMPOSE_FILE=docker-compose-all.yml
+ '[' true = true ']'
+ DOCKER_COMPOSE_FILE=docker-compose-edge.yml
+ NVM_NODEJS_ORG_MIRROR=https://nodejs.org/download/rc/
+ ELASTIC_APM_ASYNC_HOOKS=false
+ NODE_VERSION=12
...
Attaching to docker_node_tests_1
node_tests_1     | + export
node_tests_1     | + id
node_tests_1     | declare -x CASSANDRA_HOST="cassandra"
node_tests_1     | declare -x ELASTIC_APM_ASYNC_HOOKS="false"
...
node_tests_1     | + node --version
node_tests_1     | v12.0.0-rc.3
node_tests_1     | + npm --version
node_tests_1     | 6.10.1
...
node_tests_1     | + nyc report --reporter=lcov
docker_node_tests_1 exited with code 0
Aborting on container exit...
```

- Run the normal version 12
```
.ci/scripts/test.sh 12 '' false
+ DOCKER_FOLDER=.ci/docker
+ NODE_VERSION=12
+ TAV_VERSIONS=
+ IS_EDGE=false
+ case ${TAV_VERSIONS} in
+ DOCKER_COMPOSE_FILE=docker-compose-all.yml
+ '[' false = true ']'
+ NVM_NODEJS_ORG_MIRROR=https://nodejs.org/download/rc/
+ ELASTIC_APM_ASYNC_HOOKS=false
+ NODE_VERSION=12
+ TAV_VERSIONS=
++ id -u
++ id -g
+ USER_ID=501:20
+ docker-compose --no-ansi --log-level ERROR -f .ci/docker/docker-compose-all.yml up --exit-code-from node_tests --build --remove-orphans --abort-on-container-exit node_tests
Step 1/7 : ARG NODE_VERSION=8
Step 2/7 : FROM node:${NODE_VERSION}
...
node_tests_1     | + node --version
node_tests_1     | v12.5.0
node_tests_1     | + npm --version
node_tests_1     | 6.10.1
node_tests_1     | + npm install
...
```

### CODE REVIEW

**Comment by v1v** [comment]
jenkins run the tests please

**Comment by kuisathaverat** [comment]
Could we move the three stages to a downstream job and launch them in parallel? I think you can use https://github.com/elastic/apm-agent-nodejs/blob/master/.ci/downstreamTests.groovy, we 'll move TAV test to the downstream job at some point too

**Comment by kuisathaverat** [comment]
another option is to launch 3 seral stages and inside the parallel stages

**Comment by kuisathaverat** [comment]
but in any case for a second iteration

**Comment by v1v** [comment]
As we have discussed offline, this new meta-stage `Edge Test` which runs the below stages sequentially:
- `Nightly Test`
- `RC Test`
- `RC Test - No async hooks`

Is good enough for the use case of running only for the `master` branch on daily basis (triggered by a timer).

If this particular requirement changes in the future, then we might need to figure out whether to move th logic to another pipeline or do some other tweaks to run more stages in parallel for giving fast feedback, although that's something to be discussed in the future if required.

**Comment by Qard** [comment]
Looks like a commit title is too long. Also, the jenkins run appears to have been aborted?

**Comment by v1v** [comment]
@Qard , thanks for the heads up. I just fixed the commit. I didn't see any aborted builds in the jenkins pipeline, maybe I missed something, or where do you mean?

Quick feedback, I've found the linting in the commit too strict as I do use the `squash and merge`, therefore all the commits within the PR are for giving some context about something more specific than a highlevel overview. Not sure if there is an alternative about it.

**Comment by Qard** [comment]
It's only the commit title that matters, the commit body can contain whatever you want. Just need each commit to have some tag indicating type of addition and, optionally, the relevant subsystem. Just prefix everything with `ci: ` and you should be good. 🤷‍♂

**Pull request merged**
