### PR TITLE
Add .js to module path

### PR DESCRIPTION
**Pull request by vitramir**
Fix issue with bundlers like [@zeit/ncc](https://github.com/zeit/ncc)

### CODE REVIEW

**Comment by watson** [comment]
Thanks for the contribution 🙂

Could you describe a bit more about which issue you're trying to solve?

**Comment by vitramir** [comment]
@watson 
Issue is similar to this one https://github.com/zeit/ncc/issues/480
Compiled code can't resolve module without extension when using dynamic imports.

**Comment by watson** [comment]
jenkins run the tests please

**Comment by watson** [comment]
Would you mind signing our Contributor Agreement: https://www.elastic.co/contributor-agreement

If you're familiar with how to rename a commit, please also make sure your commit in this PR follows our [commit message guidelines](https://github.com/elastic/apm-agent-nodejs/blob/master/CONTRIBUTING.md#commit-message-guidelines). If you don't know how to do this, just let me know I can do it for you.

**Comment by vitramir** [comment]
I have signed Contributor Agreement. Should I do it again?

**Comment by vitramir** [comment]
Is commit message ok now?

**Comment by watson** [comment]
The commit message looks fine, thank you 👍 

Regarding the CLA: I can see that you signed with a different e-mail than the one you used in the git-commit (the one in the git-commit ends with `@icedigital.ru`). That's why the CLA-checker isn't happy. You either need to use a different e-mail in the commit or sign again using the e-mail ending with `@icedigital.ru`. Sorry for all the trouble.

**Comment by vitramir** [comment]
I have submitted new CLA

**Pull request merged**
