### PR TITLE
Make mysql2 3.x.x function

### PR DESCRIPTION
**Pull request by firecow**
From what I can tell, mysql 3.x.x doesn't contain any changes to createConnection, query or execute.

Fixes: #3151

### Checklist

- [x] Implement code
- [x] Update documentation
- [x] Add CHANGELOG.asciidoc entry
- [x] Commit message follows [commit guidelines](https://github.com/elastic/apm-agent-nodejs/blob/main/CONTRIBUTING.md#commit-message-guidelines)

### CODE REVIEW

**Comment by trentm** [comment]
@firecow Thanks for the PR! I'm looking now.

I hope you are okay with me pushing some tweaks to your branch. For example, it looks like your PR changed the package-lock.json to Windows line endings which artificially makes it look like a 27k line diff. :)

**Comment by trentm** [comment]
@firecow  Are you able to sign our CLA? (See https://github.com/elastic/apm-agent-nodejs/pull/3301#issuecomment-1529114673.)

**Comment by trentm** [comment]
Finding what versions of node mysql2 supports is a little interesting. It has:

```
  "engines": {
    "node": ">= 8.0"
  },
```

however:

- The changelog for version 2.3.1 says "build: update to node 12/14/16, migrate from travis-ci and appveyor to GH actions, add perf benchmarking workflow"
- The latest mysql2@2 is using a `lru-cache` dep with a min supported node version of v10.
- The latest mysql2@3 is using `lru-cache@8` which has a min support node version of v16.14.

**Comment by trentm** [comment]
> * The latest mysql2@3 is using `lru-cache@8` which has a min support node version of v16.14.

Attempting with node 8.6 crashes in lru-cache.

```
% node test/instrumentation/modules/mysql2/pool-release-1.test.js
/Users/trentm/el/apm-agent-nodejs-firecow/node_modules/mysql2/node_modules/lru-cache/dist/cjs/index.js:51
    heap;
        ^

SyntaxError: Unexpected token ;
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:588:28)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at Module.Hook._require.Module.require (/Users/trentm/el/apm-agent-nodejs-firecow/node_modules/require-in-the-middle/index.js:179:39)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/trentm/el/apm-agent-nodejs-firecow/node_modules/mysql2/node_modules/lru-cache/dist/cjs/index-cjs.js:5:36)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at Module.Hook._require.Module.require (/Users/trentm/el/apm-agent-nodejs-firecow/node_modules/require-in-the-middle/index.js:179:39)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/trentm/el/apm-agent-nodejs-firecow/node_modules/mysql2/lib/connection.js:25:13)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at Module.Hook._require.Module.require (/Users/trentm/el/apm-agent-nodejs-firecow/node_modules/require-in-the-middle/index.js:179:39)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/trentm/el/apm-agent-nodejs-firecow/node_modules/mysql2/index.js:5:20)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at Module.Hook._require.Module.require (/Users/trentm/el/apm-agent-nodejs-firecow/node_modules/require-in-the-middle/index.js:179:39)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/trentm/el/apm-agent-nodejs-firecow/test/instrumentation/modules/mysql2/pool-release-1.test.js:22:13)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:607:3
```

Similarly with node v12:

```
% node12 test/instrumentation/modules/mysql2/pool-release-1.test.js
/Users/trentm/el/apm-agent-nodejs-firecow/node_modules/mysql2/node_modules/lru-cache/dist/cjs/index.js:359
    #initializeTTLTracking() {
                          ^

SyntaxError: Unexpected token '('
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
...
```

It seems to work with node 14.0.0.

**Comment by trentm** [comment]
@elasticmachine, run elasticsearch-ci/docs

**Comment by trentm** [comment]
Thanks, @firecow!

**Comment by firecow** [comment]
> Thanks, @firecow!

You are welcome, and thank you for maintaining this project 🤟

**Pull request merged**
