### PR TITLE
feat(koa-router): add support for 9.x

### PR DESCRIPTION
**Pull request by watson**
This adds support for both @koa/router and koa-router v9.x

### CODE REVIEW

**Comment by JCMais** [comment]
missing version update at https://github.com/elastic/apm-agent-nodejs/blob/74f93415cea44fe5f1c2cc9481b5c0f71573eb29/lib/instrumentation/modules/koa-router.js#L9

**Comment by vigneshshanmugam** [comment]
Good catch @JCMais, Will add the fix.

**Comment by JCMais** [comment]
@watson @vigneshshanmugam do you guys have a timeframe for when these new fixes will be released?

**Comment by vigneshshanmugam** [comment]
@JCMais I am looking at some more open PR's, but in worst case it will be released before the end of this week.

**Comment by JCMais** [comment]
Thanks @vigneshshanmugam

**Pull request merged**
