### PR TITLE
feat: Add support for knex v1

### PR DESCRIPTION
**Pull request by HonzaMac**
Add support for knex v1

Refs #2699 

### Checklist

- [x] Implement code
- [x] Add tests
- [x] Update TypeScript typings
- [x] Update documentation
- [x] Add CHANGELOG.asciidoc entry
- [x] Commit message follows [commit guidelines](https://github.com/elastic/apm-agent-nodejs/blob/main/CONTRIBUTING.md#commit-message-guidelines)

### CODE REVIEW

**Comment by HonzaMac** [comment]
Any idea what to do with this?
```
ok 17 should be strictly equal
not ok 18 include user-land code frame
  ---
    operator: ok
    expected: true
    actual:   false
    at: assertBasicQuery (/Users/machalaj/msd/apm-agent-nodejs/test/instrumentation/modules/pg/knex.test.js:152:5)
    stack: |-
      Error: include user-land code frame
          at Test.assert [as _assert] (/Users/machalaj/msd/apm-agent-nodejs/node_modules/tape/lib/test.js:312:48)
          at Test.bound [as _assert] (/Users/machalaj/msd/apm-agent-nodejs/node_modules/tape/lib/test.js:95:17)
          at Test.assert (/Users/machalaj/msd/apm-agent-nodejs/node_modules/tape/lib/test.js:431:7)
          at Test.bound [as ok] (/Users/machalaj/msd/apm-agent-nodejs/node_modules/tape/lib/test.js:95:17)
          at assertBasicQuery (/Users/machalaj/msd/apm-agent-nodejs/test/instrumentation/modules/pg/knex.test.js:152:5)
          at /Users/machalaj/msd/apm-agent-nodejs/test/instrumentation/modules/pg/knex.test.js:66:7
          at Timeout._onTimeout (/Users/machalaj/msd/apm-agent-nodejs/test/_mock_http_client.js:80:7)
          at listOnTimeout (internal/timers.js:554:17)
          at processTimers (internal/timers.js:497:7)
  ...
# knex.select('c1', 'c2').from('test')
```

**Comment by trentm** [comment]
@HonzaMac Thanks for starting the PR. Just a heads up that I won't be able to take a look for at least a week.

**Comment by trentm** [comment]
I don't think I'll have time to look very soon. I gather that the knex@1 (and @2) internals are different enough that the monkey-patching in https://github.com/elastic/apm-agent-nodejs/blob/main/lib/instrumentation/modules/knex.js will need to get re-done.

**Comment by david-luna** [comment]
Hi @HonzaMac 

There were some internal changes in `knex@v1` that impacted our instrumentation making the nodejs agent blind to Postgre query builder. There is a fix for that in #3355

Next release will include support  for versions >1 <3 :)

**Pull request closed without merging**
