### PR TITLE
fix(express): improve names for routes added via app.use()

### LINKED ISSUE #1008: Express transaction names broken in v2.6.0+
**To Reproduce**
```js
require('elastic-apm-node').start();

const express = require('express');
const server = express();

// apm-agent-nodejs < 2.6.0: setting default transaction name: GET /some-path
// apm-agent-nodejs >= 2.6.0: setting default transaction name: GET unknown route
server.use('/some-path', (req, res) => {
    res.send('Hi');
});

server.listen(1212);
```

After a quick search, elastic/apm-agent-nodejs#842 looks like a possible reason.

### PR DESCRIPTION
**Pull request by watson**
Previously all `app.use()` routes would be treated as unknown routes. With this commit, only the following routes will be considered unknown:

- `app.use(fn)`
- `app.use('/', fn)`

All other routes, e.g. `app.use('/foo', fn)`, will have their transactions named accordingly. Note that the HTTP method will still be part of the transaction name, even if the route is defined using `app.use()`. I.e. `GET /foo` and `POST /foo` will be part of two different transaction groups even though they might be served by the same router function.

Fixes elastic/apm-agent-nodejs#1008

### CODE REVIEW

**Comment by MartinKolarik** [comment]
Any chance this can be merged and published as a bugfix soon?

**Comment by Qard** [comment]
This is still in-progress and @watson is on vacation right now. He should get back to it when he returns.

**Comment by watson** [comment]
@Qard Should be ready for review now. A lot in the diff is white-space related, so it reads better if you ignore that

**Comment by Qard** [comment]
Seems to be failing tests.

**Comment by watson** [comment]
Weird - not sure what changed after I rebased. Will take a look tomorrow

**Comment by watson** [comment]
Ah, it's the new handle properties test that's failing now which came from `master` because of the rebase. Somehow that test doesn't like this new route naming logic

**Comment by watson** [comment]
@Qard Fixed

**Pull request merged**
