### PR TITLE
Closes #1834 fix: Treat set-cookie in response headers as sensitive data

### LINKED ISSUE #1834: Auto filter sensitive header set-cookie not filtered for response headers
**Describe the bug**

When filterHttpHeaders is set to true (ELASTIC_APM_FILTER_HTTP_HEADERS) it's expected to redact sensitive cookie and set-cookie information from the request and response headers. This is done in http-headers.js but only the request headers and not the response headers is getting filtered. This is mainly an issue for the set-cookie in the response header.

**To Reproduce**

1. Setup the APM and set ELASTIC_APM_FILTER_HTTP_HEADERS to true (Should be true by default)
2. Do a call that have a set-cookie with a sensitive value in the response. Ex. A login request
3. Check the APM logs and check the response headers and the set-cookie shows up in clear text.

**Expected behavior**

The expected behavior is that the headers with sensitive values should be masked by the string [REDACTED]. Right now to check what is a sensitive value the node package [is-secret](https://www.npmjs.com/package/is-secret) is used. It's a good starting point but to help this along it would be desirable to be able to set additional headers and cookies that contains sensitive information.

Something like this as environment variable could be a solution:

- ELASTIC_APM_SENSETIVE_HTTP_HEADERS = auth,secreat
- ELASTIC_APM_SENSETIVE_HTTP_COOKIES = auth,private_token

**Environment (please complete the following information)**

- OS: OSX
- Node.js version: 12.18.3
- APM Server version: 7.9.2
- Agent version: 3.4.0

**How are you starting the agent? (please tick one of the boxes)**

- [X] Calling `agent.start()` directly (e.g. `require('elastic-apm-node').start(...)`)
- [ ] Requiring `elastic-apm-node/start` from within the source code
- [ ] Starting node with `-r elastic-apm-node/start`

### PR DESCRIPTION
**Pull request by StoraH**

### CODE REVIEW

**Comment by astorm** [comment]
Waiting on discussion in https://github.com/elastic/apm-agent-nodejs/issues/1834 before moving forward.

**Comment by astorm** [comment]
Thanks for bringing us this PR @StoraH ❤️  -- we're definitely interested in getting this landed.

Overall it looks like a great start.  I see we're checking the object that's passed to this function for _both_ the request and response headers now, and then passing both objects to the new `filterSensitiveHeaders` function.  This new function has the old filtering logic (which already included logic for filtering set-cookie headers). This will maintain the old behavior and ensure the response headers are filtered from spans, transactions, and errors. 

We'll need a few small additional things to get this landed.

First, it looks like the branch is out of date with master and GitHub's not happy about that.

Second, it looks like we're failing the code lint test.  You can run the lint locally via

    $ npm run lint
    
If you can get the above changes made that will let the rest of our CI run and we can take it from there.

**Comment by StoraH** [comment]
Thanks for the fast response and you described the fix as I intended  it to work so that super :D 

I updated the code to pass the lint test and think I managed to get it up to date with master. I used the button here on github to sync and it did something at least. Let me know if I need to do anything else :)

Btw, if we want this fix for the 2.x version as well do we go through the sam procedure? As far as I could see nothing have changed in the http-headers.js between the versions.

**Comment by astorm** [comment]
jenkins run the tests

**Comment by astorm** [comment]
@StoraH Step one will be getting this PR landed :)

I grabbed the latest version of your branch from this PR and was still seeing linting errors locally

```
% npm run lint

> elastic-apm-node@3.7.0 lint /Users/astorm/Documents/github/elastic/apm-agent-nodejs
> standard

standard: Use JavaScript Standard Style (https://standardjs.com)
standard: Run `standard --fix` to automatically fix some problems.
  /Users/astorm/Documents/github/elastic/apm-agent-nodejs/foo.js:3:31: Missing space before function parentheses.

...
```

Maybe you didn't push your changes back up to your GitHub host branch?

We basically want/need the checks section to be all passing/green before we can accept. 

Screen Shot 2020-11-05 at 3 27 17 PM

Right now it's showing failures.

**Comment by StoraH** [comment]
When I run `npm run lint` all is good. It look like you added some sort of test file locally called foo.js that make your test fail. I couldn't find any file called foo.js in the project. Could that be the issue?

**Comment by astorm** [comment]
jenkins run the tests

**Comment by astorm** [comment]
> Could that be the issue?

**Comment by astorm** [comment]
Thanks for your patience @storaH, we're hoping to come back to this one this week.  A few things

1. _It look like you added some sort of test file locally_ 🤦 -- right you are, my apologies for not reading the error I copy/pasted

2. It looks like the lint test that failed was/is the _commit message_ lint (`npm run lint:commit`) -- we use [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) and their rules are very -- particular.  @storaH are you comfortable rebasing and squashing/rewriting commits to bring those in line with the expectations of `npm run lint:commit`

3. We're working on landing some unrelated changes that will impact our jenkins tests -- once we land those we'll give those tests another run  and (with any luck) get this merged.

**Comment by StoraH** [comment]
@astorm okey, so I tried to do something smart when fixing the commit message issue and it seem to have closed this PR...
I now created a new PR from the same repo but with better commit message and all in one commit https://github.com/elastic/apm-agent-nodejs/pull/1886 

Hope that works and sorry about this very clumsy mistake😅

**Pull request closed without merging**
