### PR TITLE
chore: fix typo in README

### PR DESCRIPTION
**Pull request by samuelpath**
speicfy -> specify :)

### CODE REVIEW

**Comment by vigneshshanmugam** [comment]
@samuelpath Thanks for the fix. Can you sign the CLA https://www.elastic.co/contributor-agreement and also fix the commit message to follow the [conventional commits guideline](https://www.conventionalcommits.org/en/v1.0.0/#specification). 

Something like this, `chore: fix typo in README`

**Comment by samuelpath** [comment]
Thanks @vigneshshanmugam, I already signed the CLA after receiving the bot message but it's not updated in my PR. Should I ditch this PR and submit a new one?

**Comment by vigneshshanmugam** [comment]
@samuelpath The CLA works now. Thanks. 

> Should I ditch this PR and submit a new one?

Not really, just `git commit --amend` and change the commit message to `chore: fix typo in README` and push it.

**Comment by samuelpath** [comment]
Thanks @vigneshshanmugam.

I can't use `amend` since the last commit on my branch is now the merge from master:

image

I'll try to fix this using a `rebase` this week :).

**Comment by watson** [comment]
Don't worry about the commit name as we can just fix that when we merge. If that's the only part of CI that's failing we can go ahead and merge anyway.

I've just taken a look at the CLA and you have in fact signed it correctly. I'm not sure why the CI check is failing but it looks ok when I check manually 👍 It might be because it's not running the CI check again before the PR has been approved, which I've just done. So lets see what happens.

Thanks for being patient ☺️

**Comment by watson** [comment]
jenkins run the tests please

**Comment by watson** [comment]
Thanks for the help 💯

**Pull request merged**
