### PR TITLE
chore: prefix codecov.yml file with a period

### PR DESCRIPTION
**Pull request by watson**
This just makes the root a little cleaner

### CODE REVIEW

**Comment by Qard** [comment]
Actually...seems like the codecov checks disappeared. Are you sure it works with the dot? 🤔

**Comment by watson** [comment]
According to their docs yes:

> `codecov.yml` or `.codecov.yml` in the project root or any subdirectory.

_Via: https://docs.codecov.io/docs/codecov-yaml#section-repository-yaml_

**Comment by watson** [comment]
This is the build that should have done it: https://travis-ci.org/elastic/apm-agent-nodejs/jobs/405016698 - from the log it looks fine: 

<details>
<summary>Codecov output</summary>

```
----------------------------------------------|----------|----------|----------|----------|-------------------|
File                                          |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------------------------------------------|----------|----------|----------|----------|-------------------|
[32;1mAll files                                    [0m |[32;1m    80.63[0m |[33;1m    68.72[0m |[32;1m    85.61[0m |[32;1m    82.27[0m |[31;1m                  [0m |
[32;1m apm-agent-nodejs                            [0m |[32;1m      100[0m |[32;1m      100[0m |[32;1m      100[0m |[32;1m      100[0m |[33;1m                  [0m |
[32;1m  index.js                                   [0m |[32;1m      100[0m |[32;1m      100[0m |[32;1m      100[0m |[32;1m      100[0m |[33;1m                  [0m |
[32;1m apm-agent-nodejs/lib                        [0m |[32;1m    88.81[0m |[32;1m    80.81[0m |[32;1m    96.84[0m |[32;1m    90.33[0m |[31;1m                  [0m |
[32;1m  agent.js                                   [0m |[32;1m    94.18[0m |[32;1m    87.38[0m |[32;1m      100[0m |[32;1m    94.32[0m |[31;1m... 09,110,113,254[0m |
[32;1m  config.js                                  [0m |[32;1m    96.88[0m |[32;1m    84.62[0m |[32;1m      100[0m |[32;1m    96.43[0m |[31;1m             22,23[0m |
[32;1m  filters.js                                 [0m |[32;1m    81.82[0m |[32;1m    84.21[0m |[32;1m     87.5[0m |[32;1m    85.71[0m |[31;1m       48,49,50,51[0m |
[32;1m  parsers.js                                 [0m |[32;1m    81.75[0m |[33;1m    70.41[0m |[32;1m      100[0m |[32;1m    84.21[0m |[31;1m... 63,222,223,224[0m |
[32;1m  queue.js                                   [0m |[32;1m       95[0m |[32;1m       90[0m |[32;1m      100[0m |[32;1m      100[0m |[33;1m             11,12[0m |
[32;1m  request.js                                 [0m |[32;1m    83.33[0m |[32;1m    80.77[0m |[32;1m    88.89[0m |[32;1m    85.37[0m |[31;1m... 08,209,210,211[0m |
[32;1m  stackman.js                                [0m |[32;1m      100[0m |[32;1m      100[0m |[32;1m      100[0m |[32;1m      100[0m |[33;1m                  [0m |
[32;1m  symbols.js                                 [0m |[32;1m      100[0m |[32;1m      100[0m |[32;1m      100[0m |[32;1m      100[0m |[33;1m                  [0m |
[33;1m apm-agent-nodejs/lib/instrumentation        [0m |[33;1m    73.68[0m |[33;1m    60.38[0m |[33;1m    75.17[0m |[33;1m    75.13[0m |[31;1m                  [0m |
[32;1m  async-hooks.js                             [0m |[32;1m      100[0m |[32;1m      100[0m |[32;1m      100[0m |[32;1m      100[0m |[33;1m                  [0m |
[31;1m  es6-wrapped-promise.js                     [0m |[31;1m    14.29[0m |[32;1m      100[0m |[31;1m       20[0m |[31;1m    14.29[0m |[31;1m... 38,43,44,48,49[0m |
[32;1m  express-utils.js                           [0m |[32;1m    81.82[0m |[33;1m    56.25[0m |[32;1m      100[0m |[32;1m       90[0m |[31;1m                10[0m |
[32;1m  http-shared.js                             [0m |[32;1m    89.47[0m |[33;1m    78.95[0m |[32;1m      100[0m |[32;1m    88.41[0m |[31;1m... 18,120,121,123[0m |
[32;1m  index.js                                   [0m |[32;1m    93.58[0m |[32;1m    89.47[0m |[32;1m    95.24[0m |[32;1m    95.19[0m |[31;1m  67,68,92,123,124[0m |
[31;1m  patch-async.js                             [0m |[31;1m    48.76[0m |[31;1m    32.32[0m |[31;1m    46.15[0m |[33;1m    50.81[0m |[31;1m... 34,635,645,650[0m |
[33;1m  shimmer.js                                 [0m |[33;1m    61.54[0m |[33;1m    55.88[0m |[33;1m    77.78[0m |[33;1m    60.78[0m |[31;1m... 04,105,107,112[0m |
[32;1m  span.js                                    [0m |[32;1m    86.79[0m |[32;1m    82.76[0m |[32;1m    94.12[0m |[32;1m       87[0m |[31;1m... 23,124,148,156[0m |
[32;1m  timer.js                                   [0m |[32;1m      100[0m |[32;1m      100[0m |[32;1m      100[0m |[32;1m      100[0m |[33;1m                  [0m |
[32;1m  transaction.js                             [0m |[32;1m    91.95[0m |[32;1m    87.06[0m |[32;1m      100[0m |[32;1m    92.86[0m |[31;1m... 60,261,270,271[0m |
[32;1m apm-agent-nodejs/lib/instrumentation/modules[0m |[32;1m    81.84[0m |[33;1m    67.92[0m |[32;1m     89.5[0m |[32;1m    83.75[0m |[31;1m                  [0m |
[33;1m  bluebird.js                                [0m |[33;1m    65.91[0m |[33;1m       50[0m |[33;1m    63.64[0m |[33;1m    69.23[0m |[31;1m... 59,60,61,62,63[0m |
[32;1m  elasticsearch.js                           [0m |[32;1m    90.32[0m |[32;1m     91.3[0m |[32;1m      100[0m |[32;1m    93.33[0m |[31;1m             50,51[0m |
[33;1m  express-graphql.js                         [0m |[33;1m    77.78[0m |[33;1m       60[0m |[32;1m      100[0m |[32;1m    86.67[0m |[31;1m              9,10[0m |
[32;1m  express-queue.js                           [0m |[32;1m    92.31[0m |[33;1m       50[0m |[32;1m      100[0m |[32;1m      100[0m |[33;1m              6,14[0m |
[32;1m  express.js                                 [0m |[32;1m    80.82[0m |[33;1m    70.45[0m |[33;1m       75[0m |[32;1m    82.09[0m |[31;1m... 23,125,128,129[0m |
[31;1m  generic-pool.js                            [0m |[31;1m    43.59[0m |[31;1m       45[0m |[31;1m    42.86[0m |[31;1m    43.59[0m |[31;1m... 32,33,36,40,69[0m |
[32;1m  graphql.js                                 [0m |[32;1m    85.05[0m |[33;1m    72.16[0m |[32;1m      100[0m |[32;1m    87.76[0m |[31;1m... 10,166,167,171[0m |
[32;1m  handlebars.js                              [0m |[32;1m     96.3[0m |[33;1m    64.29[0m |[32;1m      100[0m |[32;1m      100[0m |[33;1m     6,22,24,40,42[0m |
[33;1m  hapi.js                                    [0m |[33;1m    74.63[0m |[33;1m    53.97[0m |[33;1m    76.92[0m |[33;1m    76.19[0m |[31;1m... ,70,71,131,156[0m |
[32;1m  http.js                                    [0m |[32;1m    96.43[0m |[32;1m    86.96[0m |[32;1m      100[0m |[32;1m      100[0m |[33;1m           7,32,35[0m |
[32;1m  http2.js                                   [0m |[32;1m    88.66[0m |[33;1m    68.18[0m |[32;1m      100[0m |[32;1m    89.13[0m |[31;1m... 29,130,132,135[0m |
[33;1m  https.js                                   [0m |[33;1m       75[0m |[33;1m    71.43[0m |[32;1m      100[0m |[32;1m    81.82[0m |[31;1m             21,22[0m |
[32;1m  ioredis.js                                 [0m |[32;1m     92.5[0m |[32;1m    83.33[0m |[32;1m      100[0m |[32;1m    94.59[0m |[31;1m             11,12[0m |
[32;1m  knex.js                                    [0m |[32;1m    93.33[0m |[33;1m       60[0m |[32;1m      100[0m |[32;1m    96.55[0m |[31;1m                15[0m |
[33;1m  koa-router.js                              [0m |[33;1m       72[0m |[33;1m    66.67[0m |[32;1m      100[0m |[33;1m       75[0m |[31;1m 10,11,20,21,31,34[0m |
[33;1m  mimic-response.js                          [0m |[33;1m    53.85[0m |[31;1m       20[0m |[33;1m       50[0m |[33;1m    58.33[0m |[31;1m    15,17,22,25,27[0m |
[32;1m  mongodb-core.js                            [0m |[32;1m    88.41[0m |[33;1m    66.67[0m |[32;1m      100[0m |[32;1m    93.75[0m |[31;1m       13,14,47,48[0m |
[32;1m  mysql.js                                   [0m |[32;1m    91.95[0m |[33;1m    76.47[0m |[32;1m      100[0m |[32;1m    92.94[0m |[31;1m... 02,103,117,118[0m |
[32;1m  mysql2.js                                  [0m |[32;1m    89.66[0m |[32;1m    84.21[0m |[32;1m      100[0m |[32;1m    89.47[0m |[31;1m 12,13,32,33,48,49[0m |
[32;1m  pg.js                                      [0m |[32;1m    83.82[0m |[33;1m    74.36[0m |[32;1m     87.5[0m |[32;1m    84.62[0m |[31;1m... ,73,74,101,134[0m |
[33;1m  redis.js                                   [0m |[33;1m    51.06[0m |[31;1m    47.22[0m |[33;1m    71.43[0m |[33;1m       50[0m |[31;1m... 67,68,70,73,76[0m |
[32;1m  ws.js                                      [0m |[32;1m    84.62[0m |[33;1m       70[0m |[32;1m      100[0m |[32;1m    83.33[0m |[31;1m        9,10,32,33[0m |
[31;1m apm-agent-nodejs/lib/middleware             [0m |[31;1m       20[0m |[32;1m      100[0m |[31;1m        0[0m |[31;1m       20[0m |[31;1m                  [0m |
[31;1m  connect.js                                 [0m |[31;1m       20[0m |[32;1m      100[0m |[31;1m        0[0m |[31;1m       20[0m |[31;1m           4,5,6,7[0m |
----------------------------------------------|----------|----------|----------|----------|-------------------|

> elastic-apm-node@1.8.3 postcoverage /home/travis/build/elastic/apm-agent-nodejs
> test/posttest.sh


travis_time:end:00adedf4:start=1531850375472150106,finish=1531850578807429410,duration=203335279304
[0K
[32;1mThe command "npm run coverage" exited with 0.[0m
travis_time:start:0afdf380
[0K$ ./node_modules/.bin/nyc report --reporter=lcov > coverage.lcov

travis_time:end:0afdf380:start=1531850578813984064,finish=1531850579716385604,duration=902401540
[0K
[32;1mThe command "./node_modules/.bin/nyc report --reporter=lcov > coverage.lcov" exited with 0.[0m
travis_time:start:0188e540
[0K$ npm install -g codecov
/home/travis/.nvm/versions/node/v8.11.3/bin/codecov -> /home/travis/.nvm/versions/node/v8.11.3/lib/node_modules/codecov/bin/codecov
+ codecov@3.0.4
added 54 packages in 1.517s

travis_time:end:0188e540:start=1531850579722390294,finish=1531850581669839229,duration=1947448935
[0K
[32;1mThe command "npm install -g codecov" exited with 0.[0m
travis_time:start:027be09e
[0K$ codecov
  _____          _  
 / ____|        | |  
| |     ___   __| | ___  ___ _____   __  
| |    / _ \ / _` |/ _ \/ __/ _ \ \ / /  
| |___| (_) | (_| |  __/ (_| (_) \ V /  
 \_____\___/ \__,_|\___|\___\___/ \_/  
                                v3.0.4
==> Detecting CI Provider
    Travis CI Detected
==> Configuration: 
    Endpoint: https://codecov.io
{ commit: '0a2ba7e45c6b1d67e8f5e198c05a59e3ad7605ff',
  branch: 'master',
  package: 'node-v3.0.4' }
==> Building file structure
==> Generating gcov reports (skip via --disable=gcov)
    $ find /home/travis/build/elastic/apm-agent-nodejs -type f -name '*.gcno'  -exec gcov  {} +
==> Scanning for reports
    + /home/travis/build/elastic/apm-agent-nodejs/coverage/lcov.info
    + /home/travis/build/elastic/apm-agent-nodejs/coverage.lcov
==> Uploading reports
    Success!
    View report at: https://codecov.io/github/elastic/apm-agent-nodejs/commit/06a89fdfcd5af1ea8939d4105e2ed538fe196599

travis_time:end:027be09e:start=1531850581676447413,finish=1531850582846569029,duration=1170121616
[0K
[32;1mThe command "codecov" exited with 0.[0m
```
</details>

**Comment by watson** [comment]
@Qard I was monitoring this when the Travis test completed and it looks like Codecov was just waiting for all tests to finish before it added the two checks. So all is good I think

**Comment by Qard** [comment]
Ah, cool. Didn't realize codecov delayed itself appearing in the list until after the other results. I would have expected an "in-progress" indicator or something, at least. 🤔

**Comment by watson** [comment]
Yeah it would be nice with a "pending" indicator. All our other CI services do that even if the tests are queued. I was looking at Codecov while this was going on and it did know it was pending. It even said so:

screen shot 2018-07-17 at 20 44 29

So it's not like it couldn't add those

**Pull request merged**
