### PR TITLE
investigating 'docker-compose down ...' failures in CI

### PR DESCRIPTION
**Pull request by trentm**
This PR is me playing with some issues with our CI being discussed in https://github.com/elastic/apm-agent-nodejs/pull/1971

**Update (20210430):** The main symptom being looked at here was tests running in docker failing at the the `docker-compose down ...` step with `error while removing network: network docker_default id cfb384f605476f50bdd4272a0a8b0e82463d64fabcca849e47f7e3e1ba24b326 has active endpoints`

### CODE REVIEW

**Comment by trentm** [comment]
```
% docker network inspect -f '{{range .Containers}}{{ .Name }} {{end}}' docker_default
docker_postgres_1 docker_cassandra_1 docker_elasticsearch_1 docker_mongodb_1 docker_mssql_1 docker_mysql_1 docker_memcached_1 docker_node_tests_1 docker_redis_1
```

^^ possibly useful if looking into https://github.com/moby/moby/issues/17217#issuecomment-196607597

**Comment by trentm** [comment]
jenkins run the module tests for @hapi/hapi,@elastic/elasticsearch

**Comment by trentm** [comment]
jenkins run the module tests for ALL

**Comment by trentm** [comment]
@v1v Could you help me understand something here? In the "checks" above there is the "TAV Test  Successful in 119m -- TAV Test" entry. That links to https://github.com/elastic/apm-agent-nodejs/pull/1974/checks?check_run_id=1875503331 instead of directly to https://apm-ci.elastic.co/job/apm-agent-nodejs/job/apm-agent-nodejs-mbp/job/PR-1974/4/testReport/

There are *two* "TAV Test" check entries, *two* "Test" check entries.  Are these coming from the ".Status" addition?

**Comment by v1v** [comment]
Uhm, they are duplicated when they should not! As far as I'm aware it's not possible :/ 

Maybe the PR initially was created with rebasing from https://github.com/elastic/apm-agent-nodejs/pull/1970

I see that those duplicated entries are pointing to different builds:

image

Points to an old build instead the latest on 

Maybe it does not work correctly with GitHub comments, I need to see if I can reproduce it

**Comment by trentm** [comment]
> Maybe the PR initially was created without #1970

Ah, perhaps. That sounds likely. Thanks. No need to bother trying to reproduce here. I'll bring it up if I see it happen again.

**Comment by trentm** [comment]
Closing. This isn't a useful experiment right now. I will engage again if we start seeing the symptom again. A starter patch for the record might be:

```
diff --git a/.ci/scripts/test.sh b/.ci/scripts/test.sh
index b902b85..9f4fcf2 100755
--- a/.ci/scripts/test.sh
+++ b/.ci/scripts/test.sh
@@ -133,8 +133,12 @@ docker-compose \
   --abort-on-container-exit \
   node_tests

-NODE_VERSION=${NODE_VERSION} docker-compose \
-  --no-ansi \
-  --log-level ERROR \
-  -f ${DOCKER_FOLDER}/${DOCKER_COMPOSE_FILE} \
-  down -v
+if ! NODE_VERSION=${NODE_VERSION} docker-compose \
+    --no-ansi \
+    --log-level ERROR \
+    -f ${DOCKER_FOLDER}/${DOCKER_COMPOSE_FILE} \
+    down -v; then
+  docker network inspect docker_default || true
+  docker network inspect -f '{{range .Containers}}{{ .Name }} {{end}}' docker_default || true
+  exit 1
+fi
```

**Pull request closed without merging**
