### PR TITLE
chore(config): update flushInterval to 10 seconds

### LINKED ISSUE #175: Use lower default value for flushInterval config option
The [`flushInterval`](https://www.elastic.co/guide/en/apm/agent/nodejs/current/agent-api.html#flush-interval) config option currently defaults to 60 seconds. This is too long and we should decide on a better default.

### PR DESCRIPTION
**Pull request by Qard**
Fixes #175

### CODE REVIEW

**Comment by watson** [comment]
The tests fails here:

https://github.com/elastic/apm-agent-nodejs/blob/d3f28c18824b4e81319e5aa406c213ee6ece3de4/test/instrumentation/modules/http/aborted-requests-disabled.js#L95

Not really sure why that is though. Doesn't seem directly related to the `flushInterval` 🤔

**Comment by watson** [comment]
This PR could have gone to master as it doesn't contain any 6.2 related changes. But we can just cherry-pick it into master once it's merged as there's no way to change the destination branch of a PR.

**Comment by Qard** [comment]
Fixed. It was just a timing thing.

**Comment by watson** [comment]
@Qard Travis and Jenkins had several outages last night, and so I merged this too quickly. Turns out the real course of the bug you fixed by changing a `setTimeout` to a `setImmediate` was that `flushInterval` became `NaN` as the mocked agent didn't have the property set, so it was `undefined`. I discovered it in master, amended the commit [with a fix](https://github.com/elastic/apm-agent-nodejs/commit/c3cfc9a41f188fe22e653271c5aff2555599841e#diff-728d83d6dd614acedce1051318b9f7b5R21), and force pushed.

**Comment by Qard** [comment]
Ah, good catch.

**Pull request merged**
