### PR TITLE
feat(parsers): collect error causes

### LINKED ISSUE #1196: Look into supporting chained exceptions
We're adding support for chained exceptions in Elastic APM (see elastic/apm#40).

However, we don't have a way to chain in exceptions in Node.js, but I was thinking we might provide an API that allows the user to record such things.

E.g. it's not uncommon in Node.js to say get a low-level error back from the database driver and then throw a more high-level error. Having access to both the low and the high-level error would be useful.

### PR DESCRIPTION
**Pull request by Qard**
Fixes elastic/apm-agent-nodejs#1196

### Checklist

- [x] Implement code
- [x] Add tests

### CODE REVIEW

**Comment by AnandChowdhary** [comment]
Hi @trentm and @graphaelli,

I contacted @Qard about requesting the npm package name `causes` (for a "developers can support causes like BLM in their projects"-kind of project), and they told me that since they made this package as part of this PR, I should ask Elastic whether they'd be up to letting me have it.

If you don't have any use for it for the time being, I'd love to have you consider this! 

http://npmjs.com/package/causes - I'm on npm as @`anandchowdhary`

**Comment by trentm** [comment]
@AnandChowdhary (/cc @Qard), I am fine with passing the "causes" package name on.  

I'll close this PR -- once https://github.com/elastic/apm-agent-nodejs/pull/2094 goes in, this PR would need to be re-written or deal with the merge conflict.

**Comment by Qard** [comment]
I've handed over the module. If you choose to revisit this and would like to make use of the code I had previous written, it's currently available at https://github.com/qard/causes. Feel free to use it, or not, as you choose. Happy to hand over the code rights or whatever. :)

**Comment by trentm** [comment]
@Qard Thanks!

**Pull request closed without merging**
