### PR TITLE
ci: avoid spurious TAV Test failure from not having TAP output

### LINKED ISSUE #1844: ci: daily "TAV Test" Jenkins steps all fail on tap2Junit
Once per day [the TAV tests are run](https://github.com/elastic/apm-agent-nodejs/blob/403bda833422264fa3246973faf7b7e08cdb0650/.ci/schedule-daily.groovy#L48).
Every sub-step/build of "TAV Test" fails, e.g.:
https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-nodejs%2Fapm-agent-nodejs-mbp/detail/master/636/pipeline

Each of those steps' logs (e.g. https://apm-ci.elastic.co/blue/rest/organizations/jenkins/pipelines/apm-agent-nodejs/pipelines/apm-agent-nodejs-mbp/branches/master/runs/636/nodes/1271/log/?start=0) ends with:

```
...
[2020-10-29T06:18:42.358Z] Status: Downloaded newer image for node:12-alpine
[2020-10-29T06:18:46.555Z] /tmp/.npm-global/bin/tap-xunit -> /tmp/.npm-global/lib/node_modules/tap-xunit/bin/tap-xunit
[2020-10-29T06:18:46.555Z] /tmp/.npm-global/bin/txunit -> /tmp/.npm-global/lib/node_modules/tap-xunit/bin/tap-xunit
[2020-10-29T06:18:46.555Z] + tap-xunit@2.4.1
[2020-10-29T06:18:46.555Z] added 21 packages from 21 contributors in 1.802s
script returned exit code 1
```

This `tap2Junit` was introduced in July in https://github.com/elastic/apm-agent-nodejs/pull/1794
I think that change introduced this breakage.

Here is a manual repro:

```
% TAV=ioredis npm run test:tav|tee tav-output.tap
...

% npm install tap-xunit
npm WARN express-graphql@0.9.0 requires a peer of graphql@^14.4.1 but none is installed. You must install peer dependencies yourself.
npm WARN graphql-subscriptions@1.1.0 requires a peer of graphql@^0.10.5 || ^0.11.3 || ^0.12.0 || ^0.13.0 || ^14.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN graphql-upload@8.1.0 requires a peer of graphql@0.13.1 - 14 but none is installed. You must install peer dependencies yourself.

+ tap-xunit@2.4.1
added 10 packages from 7 contributors and audited 1663 packages in 5.132s

81 packages are looking for funding
  run `npm fund` for details

found 26 vulnerabilities (15 low, 8 high, 3 critical)
  run `npm audit fix` to fix them, or `npm audit` for details

% cat tav-output.tap | ./node_modules/.bin/tap-xunit --package="Node.js"

% echo $?
1
```

That tav-output.tap looks like this:
https://gist.github.com/trentm/b96cd5fc54e0bde88979652f1491d0a2

The surprise here is that the "TAV Test" output (i.e. from running `npm run test:tav`), **isn't TAP**.

Before https://github.com/elastic/apm-agent-nodejs/pull/1794 the script doing the TAP-to-jUnit conversion used `|| true` to never fail: https://github.com/elastic/apm-agent-nodejs/pull/1794/files#diff-c3d507573a93fc56cfff064df1b4e453582b90d43b22ceb3b6b8ade7ee2bb42fL13

```
    cat ${tf}|tap-junit --package="Agent Node.js" > junit-${filename}-report.xml || true
```

Would it be reasonable to use the following to get the same behaviour?

```diff
diff --git a/.ci/Jenkinsfile b/.ci/Jenkinsfile
index 337b833..543157d 100644
--- a/.ci/Jenkinsfile
+++ b/.ci/Jenkinsfile
@@ -380,7 +380,7 @@ def generateStep(Map params = [:]){
           } catch(e){
             error(e.toString())
           } finally {
-            tap2Junit(pattern: '*-output.tap', suffix: 'junit.xml', package: 'Node.js')
+            tap2Junit(pattern: '*-output.tap', suffix: 'junit.xml', package: 'Node.js', failNever: true)
             codecov(repo: env.REPO, basedir: '.', secret: "${CODECOV_SECRET}")
           }
         }
```

### PR DESCRIPTION
**Pull request by trentm**
Fixes #1844

### CODE REVIEW

**Comment by v1v** [comment]
+1

You might need to use the comment to run all the TAV within this PR.  I don't recall now what's the one, but I can look it at tomorrow morning

**Comment by trentm** [comment]
jenkins run the module tests for ALL

**Review by v1v — APPROVED** [review]
Looks good to me

**Comment by trentm** [comment]
Still merging even with failing TAV tests. This gets us much further along: errors for those that are actually failing, warnings for the rest on the empty tav2Junit output.

**Pull request merged**
