### PR TITLE
tests: reduce the number of versions of jade being tested

### PR DESCRIPTION
**Pull request by trentm**
Jade was renamed to pug and hasn't had a release since 2015. Testing
114 releases of jade for every commit is unnecessary.

This also adds examples for the other two templating libs.

- [x] run TAV=pug,handlebars,jade tests

### CODE REVIEW

**Comment by trentm** [comment]
Some data on the justification for reducing the number of jade versions being tested with TAV:

`>0.5.5` matches 114 releases:

```
$ TAV=jade ./node_modules/.bin/tav --verbose
...
-- package versions matching ">0.5.5": 0.5.6, 0.5.7, 0.6.0, 0.6.1, 0.6.3, 0.7.0, 0.7.1, 0.8.0, 0.8.1, 0.8.2, 0.8.3, 0.8.4, 0.8.5, 0.8.6, 0.8.7, 0.8.8, 0.8.9, 0.9.0, 0.9.1, 0.9.2, 0.9.3, 0.10.0, 0.10.1, 0.10.2, 0.10.3, 0.10.4, 0.10.5, 0.10.6, 0.10.7, 0.11.0, 0.11.1, 0.12.0, 0.12.1, 0.12.2, 0.12.3, 0.12.4, 0.13.0, 0.14.0, 0.14.1, 0.14.2, 0.15.0, 0.15.1, 0.15.2, 0.15.3, 0.15.4, 0.16.0, 0.16.1, 0.16.2, 0.16.3, 0.16.4, 0.17.0, 0.18.0, 0.19.0, 0.20.0, 0.20.1, 0.20.2, 0.20.3, 0.21.0, 0.22.0, 0.22.1, 0.23.0, 0.24.0, 0.25.0, 0.26.0, 0.26.1, 0.26.2, 0.26.3, 0.27.0, 0.27.1, 0.27.2, 0.27.3, 0.27.4, 0.27.5, 0.27.6, 0.27.7, 0.28.0, 0.28.1, 0.28.2, 0.29.0, 0.30.0, 0.31.0, 0.31.1, 0.31.2, 0.32.0, 0.33.0, 0.34.0, 0.34.1, 0.35.0, 1.0.0, 1.0.1, 1.0.2, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.2.0, 1.3.0, 1.3.1, 1.4.0, 1.4.1, 1.4.2, 1.5.0, 1.6.0, 1.7.0, 1.8.0, 1.8.1, 1.8.2, 1.9.0, 1.9.1, 1.9.2, 1.10.0, 1.11.0
...
```

Because of that, the jade TAV test steps in Jenkins are typically in the top 30 slowest:

```
% ./dev-utils/jenkins-build-slow-steps.sh https://apm-ci.elastic.co/job/apm-agent-nodejs/job/apm-agent-nodejs-mbp/job/master/1189/
...
923656 FINISHED SUCCESS .ci/scripts/test.sh -b "release" -t "express" "8"
931443 FINISHED SUCCESS .ci/scripts/test.sh -b "release" -t "ioredis" "10"
931727 FINISHED SUCCESS .ci/scripts/test.sh -b "release" -t "jade" "8"
940257 FINISHED SUCCESS .ci/scripts/test.sh -b "release" -t "mongodb-core" "10"
951753 FINISHED SUCCESS .ci/scripts/test.sh -b "release" -t "apollo-server-express" "17"
963197 FINISHED SUCCESS .ci/scripts/test.sh -b "release" -t "fastify" "14"
963903 FINISHED SUCCESS .ci/scripts/test.sh -b "release" -t "express" "12"
976377 FINISHED SUCCESS .ci/scripts/test.sh -b "release" -t "ioredis" "14"
995583 FINISHED SUCCESS .ci/scripts/test.sh -b "release" -t "mongodb-core" "14"
1016700 FINISHED SUCCESS .ci/scripts/test.sh -b "release" -t "ioredis" "8"
1027583 FINISHED SUCCESS .ci/scripts/test.sh -b "release" -t "hapi" "8"
1056519 FINISHED SUCCESS .ci/scripts/test.sh -b "release" -t "jade" "10"
1061457 FINISHED SUCCESS .ci/scripts/test.sh -b "release" -t "jade" "12"
1078192 FINISHED SUCCESS .ci/scripts/test.sh -b "release" -t "knex" "8"
1084905 FINISHED SUCCESS .ci/scripts/test.sh -b "release" -t "tedious" "14"
1096873 FINISHED SUCCESS .ci/scripts/test.sh -b "release" -t "bluebird" "8"
1103094 FINISHED SUCCESS .ci/scripts/test.sh -b "release" -t "mongodb-core" "8"
1106538 FINISHED SUCCESS .ci/scripts/test.sh -b "release" -t "got" "12"
1126269 FINISHED SUCCESS .ci/scripts/test.sh -b "release" -t "bluebird" "12"
1127391 FINISHED SUCCESS .ci/scripts/test.sh -b "release" -t "fastify" "10"
1140066 FINISHED SUCCESS .ci/scripts/test.sh -b "release" -t "hapi" "12"
1180374 FINISHED SUCCESS .ci/scripts/test.sh -b "release" -t "hapi" "10"
1185804 FINISHED SUCCESS .ci/scripts/test.sh -b "release" -t "mongodb-core" "12"
1206561 FINISHED SUCCESS .ci/scripts/test.sh -b "release" -t "pg" "12"
1209525 FINISHED SUCCESS .ci/scripts/test.sh -b "release" -t "graphql" "8"
1213366 FINISHED SUCCESS .ci/scripts/test.sh -b "release" -t "bluebird" "10"
1233347 FINISHED SUCCESS .ci/scripts/test.sh -b "release" -t "knex" "10"
1234987 FINISHED SUCCESS .ci/scripts/test.sh -b "release" -t "graphql" "12"
1248705 FINISHED SUCCESS .ci/scripts/test.sh -b "release" -t "pg" "8"
1250563 FINISHED SUCCESS .ci/scripts/test.sh -b "release" -t "pg" "10"
1271174 FINISHED SUCCESS .ci/scripts/test.sh -b "release" -t "apollo-server-express" "8"
1278278 FINISHED SUCCESS .ci/scripts/test.sh -b "release" -t "jade" "14"
1301008 FINISHED SUCCESS .ci/scripts/test.sh -b "release" -t "graphql" "10"
1301168 FINISHED SUCCESS .ci/scripts/test.sh -b "release" -t "knex" "14"
1362381 FINISHED SUCCESS .ci/scripts/test.sh -b "release" -t "ioredis" "12"
1390452 FINISHED SUCCESS .ci/scripts/test.sh -b "release" -t "apollo-server-express" "10"
1419095 FINISHED SUCCESS .ci/scripts/test.sh -b "release" -t "bluebird" "14"
1463949 FINISHED SUCCESS .ci/scripts/test.sh -b "release" -t "apollo-server-express" "12"
1475109 FINISHED SUCCESS .ci/scripts/test.sh -b "release" -t "graphql" "14"
1597508 FINISHED SUCCESS .ci/scripts/test.sh -b "release" -t "knex" "12"
1806122 FINISHED SUCCESS .ci/scripts/test.sh -b "release" -t "apollo-server-express" "14"
```

And showing jade hasn't been released since 2015:

```
$ npm info -j jade
  "time": {
    "modified": "2018-08-03T00:38:50.126Z",
    "created": "2010-12-19T22:37:03.716Z",
    "0.0.1": "2010-12-19T22:37:03.716Z",
...
    "0.5.5": "2010-12-19T22:37:03.716Z",
...
    "1.10.0": "2015-05-25T11:28:32.931Z",
    "1.11.0": "2015-06-12T05:13:07.515Z"
  },
```

**Comment by trentm** [comment]
run modules tests for pug,handlebars,jade

**Comment by trentm** [comment]
run module tests for pug,handlebars,jade

**Comment by trentm** [comment]
TAV test run with be build 2 at https://apm-ci.elastic.co/job/apm-agent-nodejs/job/apm-agent-nodejs-mbp/job/PR-2473/

**Comment by trentm** [comment]
run module tests for pug,handlebars,jade

**Comment by trentm** [comment]
run module tests for pug,handlebars,jade

**Review by astorm — APPROVED** [review]
👍 approving. Seems a reasonable version compromise for an old package.

**Pull request merged**
