### PR TITLE
feat(transaction): span_count.total

### LINKED ISSUE #552: Add `transaction.span_count.total`
Implement https://github.com/elastic/apm-server/issues/1241

### PR DESCRIPTION
**Pull request by Qard**
Fixes elastic/apm-agent-nodejs#552
Depends on elastic/apm-agent-nodejs#557

### Checklist

- [x] Implement code
- [x] Add tests

### CODE REVIEW

**Comment by Qard** [comment]
One as-yet unanswered question is if span_count should be null on unsampled transactions.

**Comment by watson** [comment]
The tests fail because of #554

I don't like `span_count === null` when the transaction is upsampled to be honest. I know about the performance implications, but it also just feels "unclean" to send up these JSON objects containing `null` objects. But I'm not sure if it's just vanity or if there's something deeper 🤔

**Comment by Qard** [comment]
By that, do you mean you'd prefer the `span_count` is _always_ present, or that it should be `undefined`?

**Comment by watson** [comment]
I mean that I prefer the JSON document not to include it for un-sampled transactions. There's a lot of optional fields in our payload that I feel would be weird if they were reported as `null`. But the APM Server will just ignore them (I assume), so I guess there's no technical problem in keeping it as `null`.

**Comment by Qard** [comment]
I _think_ explicitly defining them as `undefined` should avoid the hidden-class problem the same as defining as `null` does. We could try that.

**Comment by Qard** [comment]
Rebased with #557 to get tests passing.

**Comment by Qard** [comment]
Updated to reflect the current state of the decision in https://github.com/elastic/apm-server/issues/1241.

**Comment by Qard** [comment]
I've also changed the `dropped.total` to `dropped`, as suggested in https://github.com/elastic/apm-server/issues/1241#issuecomment-419977863.

**Comment by watson** [comment]
Should this PR be rebased or squashed and merged?

**Comment by Qard** [comment]
Could squash and merge, if you edit the commit title/message to describe all the changes. Rebase is fine too though.

**Pull request merged**
