### PR TITLE
fix: avoid throwing when agent is in active: false mode

### PR DESCRIPTION
**Pull request by bsyk**
Add check for whether the agent is active before trying to increment counters.  This avoids the issue of throwing when a counter is non-existent due to the agent being inactive.

Fixes: elastic/apm-agent-nodejs#1257

### Checklist

- [x] Implement code
- [x] Add tests
- [ ] Update documentation

### CODE REVIEW

**Comment by bsyk** [comment]
@watson can I get some eyes on this small PR please?

**Comment by Qard** [comment]
I think it'd probably be better that we just move the logic for _using_ the counter interface into `lib/metrics/index.js` and do the check there rather than here as this issue would exist _anywhere_ that there's a counter being used. 🤔

**Comment by bsyk** [comment]
Currently, Counter is only use within Transaction as far as I can tell.
Are you proposing a better 'started' check within Metrics to protect against `this[registrySymbol]` being null during this call?

```
getOrCreateCounter (...args) {
  return this[registrySymbol].getOrCreateCounter(...args)
}
```

**Comment by Qard** [comment]
I'm proposing _replacing_ that with something like `incrementCounter(name, amount)` with an early-return if not active. The issue currently is that the code is _expecting_ that to return an object that it can call `inc(...)` on, which won't be the case if not active.

**Comment by Qard** [comment]
Also, the reason for putting the check _there_ versus in that breakdown metrics code is that we may _in the future_ decide we want to capture _more_ metrics in _other_ places and would then need to duplicate that check everywhere else too. It's better to have a central place where the check happens, that way we don't accidentally miss it again in the future.

**Comment by bsyk** [comment]
Makes sense. I'll update with a change that reflects that tomorrow.

**Comment by Qard** [comment]
jenkins run the tests please

**Comment by bsyk** [comment]
I can't reproduce the jenkins build failure locally - has this test been an issue in the past?

**Comment by Qard** [comment]
jenkins run the tests please

**Comment by watson** [comment]
This has now been released in v2.16.1 - Thanks again for fixing this 💯

**Pull request merged**
