### PR TITLE
feat(jenkins): new notifications and reports to Elasticsearch

### PR DESCRIPTION
**Pull request by kuisathaverat**
* new notifications and reports to Elasticsearch
Screenshot 2019-06-05 at 12 57 54

### CODE REVIEW

**Comment by kuisathaverat** [comment]
on the new notification at bottom, you would have a set of links to the Jenkins UI and one to go to a Kibana instance where we will store info related with each build, result, duration, general info, tests results, artifacts, changes, ... with that data we would create a set of dashboards to extract stats an other insights

**Comment by watson** [comment]
@kuisathaverat Sorry this wasn't supposed to be merged yet as the commit message was wrong (I could just have done that my self, but wanted to hear your reply first). I tired to "undo" the accept by chaning it to a comment, but GitHub apparently doesn't allow you to redact and "Accept". I'll just rebase and force push master 😅 

In the future please remember that all commits related to tests or CI has to start with either `ci` or `test` or `chore`. If you use `feat` it will result in a bump of the minor version at the next release.

**Comment by watson** [comment]
Oh I also just saw that this PR was merged into the 2.x branch. We're not supposed to merge anything into that branch as it will be overwritten with the content of master at every release. I'll remove the commit for now and figure out what to do

**Comment by watson** [comment]
I just made a new PR (#1116) - that was easiest 😄 Sorry so we have so many weird workflow rules

**Comment by kuisathaverat** [comment]
sorry for the inconveniences.

**Pull request merged**
