### PR TITLE
feat(*): add full to url

### PR DESCRIPTION
**Pull request by Qard**
Fixes: #106

### CODE REVIEW

**Comment by watson** [comment]
@beniwohli you mentioned at some point something about some HTTP headers that were added by certain proxies, load balancers etc. that would hold information about the original URL or host. Do you remember what those were?

**Comment by beniwohli** [comment]
@watson can't think of any. I did mention that WSGI has environment variables that contain certain information about the host/path: https://www.python.org/dev/peps/pep-0333/#environ-variables

**Comment by AdriVanHoudt** [comment]
Google cloud load balancer adds headers like `X-Forwarded-For` and `X-Forwarded-Proto`

**Comment by beniwohli** [comment]
`X-Forwarded-For` contains the original IP of of the caller (or a list of IPs) AFAIK, so I don't think it'll help in this case

**Comment by AdriVanHoudt** [comment]
@beniwohli hmm true, the `X-Forwarded-Proto` contains the original protocol (http/https) so that would be useful
@watson looking forward to that one

**Comment by watson** [comment]
Finished the original-url module now: https://github.com/watson/original-url

@Qard let me know what you think

**Comment by Qard** [comment]
@watson Are we intending to drop the `raw` field? It seems to not be included in the output of original-url.

**Comment by watson** [comment]
@Qard We'll keep the `raw` field. The only reason why I didn't include it in the returned object from the "original-url" module was because I thought that it was too specific to our use-case and because it's easy to add manually to the returned objected afterwards. But as we talked about in other channels, let's just add it to "original-url" anyway.

**Comment by watson** [comment]
I've released v1.1.0 of original-url which includes your PR adding raw to the result

**Comment by Qard** [comment]
updated.

**Comment by Qard** [comment]
rebased.

**Pull request merged**
