### PR TITLE
feat: support express-graphql 0.10.0 - 0.12.0

### PR DESCRIPTION
**Pull request by trentm**
Closes: #2507
Fixes: #2424

### Checklist

- [x] Implement code
- [x] Add tests
- [x] Update documentation
- [x] Add CHANGELOG.asciidoc entry
- [x] Commit message follows [commit guidelines](https://github.com/elastic/apm-agent-nodejs/blob/master/CONTRIBUTING.md#commit-message-guidelines)
- [x] Skip testing express-graphql on node `<10.4.0` (see comment below)
- [x] Full TAV run. Also evaluate whether express-graphql TAV tests are taking too much time, because of the large matrix.
- [x] Add a top-comment explaining the point of the `trans._graphqlRoute`
- [x] Perhaps add examples/trace-express-graphql.js from the example I had for #2424

### CODE REVIEW

**Comment by trentm** [comment]
There is some issue with express-graphql `>=0.10.0` and node `<10.4` such that the wrapped `graphql.execute` called by express-graphql is not in the run context of the transaction, so the graphql span does not get created and the transaction does not get marked as a GraphQL transaction.

It works with express-graphql@0.9.0, FWIW.  I'm not sure what is going on; but I'm also not sure it is worth supporting given node v10 is EOL at this point.

**Comment by trentm** [comment]
run module tests for express-graphql

**Comment by trentm** [comment]
run module tests

**Comment by trentm** [comment]
>  Full TAV run. Also evaluate whether express-graphql TAV tests are taking too much time, because of the large matrix.

https://apm-ci.elastic.co/job/apm-agent-nodejs/job/apm-agent-nodejs-mbp/job/PR-2511/6/

**Comment by trentm** [comment]
run module tests for ALL

**Comment by trentm** [comment]
run module tests for ALL

**Review by astorm — APPROVED** [review]

**Pull request merged**
