### PR TITLE
chore(deps-dev): update fastify to 5.0.0 and @fastify/formbody to 8.0.1

### PR DESCRIPTION
**Pull request by david-luna**
`fastify` and `@fastify/formbody` should be updated at once. This PR supersedes #4246 and #4247 

### Checklist

- [X] Update tests
- [ ] Add CHANGELOG.asciidoc entry
- [X] Commit message follows [commit guidelines](https://github.com/elastic/apm-agent-nodejs/blob/main/CONTRIBUTING.md#commit-message-guidelines)

### CODE REVIEW

**Review by trentm — DISMISSED** [review]
Probably also want an update to .tav.yml for this (in this or a separate PR).

**Comment by david-luna** [comment]
> Probably also want an update to .tav.yml for this (in this or a separate PR).

thanks for you thorough review. I forgot about TAV 😓
I'll do it here

**Review by david-luna — COMMENTED** [review]
/test tav

**Review by trentm — APPROVED** [review]
Nice. Thanks.

**Pull request merged**
