### PR TITLE
tests: fix docker-compose setup that broke aws-sdk TAV tests in CI

### PR DESCRIPTION
**Pull request by trentm**
Fixes: #2129

### CODE REVIEW

**Comment by trentm** [comment]
https://apm-ci.elastic.co/job/apm-agent-nodejs/job/apm-agent-nodejs-mbp/job/PR-2132/2/ is a test run of the TAV tests, which passed.

The initial test run that resulted in the failed "apm-ci/branch" and "Test" checks is from https://apm-ci.elastic.co/job/apm-agent-nodejs/job/apm-agent-nodejs-mbp/job/PR-2132/1/ which failed *one* of the test matrix tests at the end with the spurious:

```
[2021-06-28T18:32:44.078Z] error while removing network: network docker_default id f2189e6b5e70c836f5f31784476c2f29f7c84a0bc6e4e47547d6539061caa63c has active endpoints
```

I'll re-run those tests.

**Comment by trentm** [comment]
jenkins run the tests

**Comment by trentm** [comment]
Tests passed on the re-run. The current failed "apm-ci/branch" check still points to build 1. Is this a bug that it isn't updated for a new test run via `jenkins run the tests`? Don't know.

**Comment by trentm** [comment]
> The current failed "apm-ci/branch" check still points to build 1. Is this a bug that it isn't updated for a new test run via `jenkins ...sts`? Don't know.

I think this is a bug in the Jenkinsfile reporting, which is out of scope for this ticket.

**Review by astorm — APPROVED** [review]
👍 whatever keeps the ~spice~ tests flowing.

**Pull request merged**
