### PR TITLE
fix: drop no-longer-necessary half-disabling of instrumentations

### PR DESCRIPTION
**Pull request by trentm**
When disableInstrumentations support was added in #353 it only
half-disabled these instrumentations, briefly mentioning "continuation
patches". I believe this was about user-land callback queue handling
that should no longer be necessary after run-context and #2430 work.

In #2498 it was discussed and decided that if listed in 
`disableInstrumentations` the agent should not touch the module at all.

### Checklist

- [x] Implement code: update from main, this is currently a bit out of date.
- [x] Test with TAV run.
- [x] Add CHANGELOG.asciidoc entry (an entry was added in the [3.26.0 release](https://github.com/elastic/apm-agent-nodejs/pull/2505/files)).

### CODE REVIEW

**Comment by trentm** [comment]
run module tests for mysql,pg,redis,ioredis

**Comment by trentm** [comment]
@elastic/observablt-robots Would one of you be able to look into why the `run module tests for mysql,pg,redis,ioredis` comment above did not do anything? https://apm-ci.elastic.co/job/apm-agent-nodejs/job/apm-agent-nodejs-mbp/job/PR-2444/ only has the original build from when this PR was opened.

**Comment by cachedout** [comment]
>  Would one of you be able to look into why the run module tests for mysql,pg,redis,ioredis comment above did not do anything? 

Paging @elastic/observablt-robots-on-call

**Comment by v1v** [comment]
> Would one of you be able to look into why the run module tests for mysql,pg,redis,ioredis comment above did not do anything? 

IIUC, `run module tests for mysql,pg,redis,ioredis` matches `^run (module|benchmark) tests`, but it's not, it should be `^run (module|benchmark) tests .*` 

image


Let me put a fix

**Comment by trentm** [comment]
run module tests for redis,mysql

**Review by astorm — APPROVED** [review]

**Pull request merged**
