### PR TITLE
test: add tedious to Jenkins TAV matrix

### LINKED ISSUE #477: Add tedious to Jenkins TAV matrix
We forgot to add it in elastic/apm-agent-nodejs#444

### PR DESCRIPTION
**Pull request by watson**
Fixes #477

### CODE REVIEW

**Comment by watson** [comment]
jenkins, run tav tests please

**Comment by Qard** [comment]
Ugh...seems the order of prepare and execute spans is non-deterministic. I'll fix the tests. 😓

**Comment by Qard** [comment]
This should be fixed by #479.

**Comment by watson** [comment]
jenkins, run tav tests please

**Comment by watson** [comment]
@Qard I merge your PR into master and rebased, but it unfortunately didn't solve the problem. Maybe try to push a fix to this PR to make it easier to see if it actually fixes it.

**Comment by watson** [comment]
Superseded by #481

**Pull request closed without merging**
