### PR TITLE
test(ci): test unreleased versions of Node.js

### PR DESCRIPTION
**Pull request by watson**
Should we add others than `nightly` and `rc`?

See a full list of possibilities here: https://nodejs.org/download/

### CODE REVIEW

**Comment by watson** [comment]
@Qard currently the release candidates of Node.js 10 and 11 breaks our builds: https://travis-ci.org/elastic/apm-agent-nodejs/builds/380357638

Should we still merge or do we want to check what's going on first?

**Comment by Qard** [comment]
It only gets triggered by cron, so I think it's fine to have failures we are aware of.

**Comment by watson** [comment]
Hmmm yeah, I'm just worried about having a cron job that have certain tests that are continuously failing but also contain tests that - if they fail - should require immediate action (the TAV tests).

Maybe we should just have a look at why the two nightly tests are failing to see if it's a simple fix or if it's something more fundamental.

**Comment by Qard** [comment]
Is there any way to group into different cron tasks so we could have one that's just RCs and one that is just TAV tests? Then we could pull all that out of the per-commit tests and run those two groups periodically, tracking the TAV results more closely.

**Comment by watson** [comment]
The only way that I know of is to make that dummy branch that I did in #360 and have that contain a custom `.travis.yml` file that checks out master before running the tests. That way you can have a separate cron job on that branch, which will even produce slightly different failure mails so you can differentiate directly in the e-mail subject.

**Pull request merged**
