### PR TITLE
Fix graphql error handling (#1)

### PR DESCRIPTION
**Pull request by dpoetzschke**
Fixes module graphqls error handling with syntax errors in queries

On our project we ran into the problem, that elastic-apm-node would break the working integration of graphql in our app.
Instead of returning a Promise.resolve() with an error object graphql() will throw an error when used with elastic-apm-node.

The pr will fix this behavior by adding a try/catch around the query parsing.

I hope i didn't miss any steps required for this PR.
- testing was done via `npm test all 10 graphql ` and returned "OK"

elastic/apm-agent-nodejs#746

### CODE REVIEW

**Comment by elasticcla** [comment]
Hi @dpoetzschke, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/elastic/apm-agent-nodejs/pull/747.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by dpoetzschke** [comment]
Not quite sure how to solve the email issue, since my CLA email is the main linked to this account.

**Comment by watson** [comment]
@dpoetzschke Thanks for tracking down and fixing this issue. I'll look into the CLA problem you're seeing, but in the meantime could I get you to do two things for me:

1) Change the commit message to be `fix(graphql): don't throw on invalid query`. This will fix the commit message linting error
2) Add a test to see that this fix works as expected

I've already made a test that you can just include - I can also just push it to this PR if you like, or you can add it yourself from this diff:

```diff
diff --git a/test/instrumentation/modules/graphql.js b/test/instrumentation/modules/graphql.js
index aa71493..ae0146a 100644
--- a/test/instrumentation/modules/graphql.js
+++ b/test/instrumentation/modules/graphql.js
@@ -31,6 +31,26 @@ test('graphql.graphql', function (t) {
   })
 })
 
+test('graphql.graphql - invalid query', function (t) {
+  resetAgent(done(t, 'Unkown Query'))
+
+  var schema = graphql.buildSchema('type Query { hello: String }')
+  var root = { hello () {
+    return 'Hello world!'
+  } }
+  var query = '{ hello'
+
+  agent.startTransaction('foo')
+
+  graphql.graphql(schema, query, root).then(function (response) {
+    agent.endTransaction()
+    t.deepEqual(response, { errors: [
+      { message: 'Syntax Error: Expected Name, found <EOF>', locations: [ { line: 1, column: 8 } ] }
+    ] })
+    agent.flush()
+  })
+})
+
 test('graphql.execute', function (t) {
   resetAgent(done(t))
 
@@ -98,7 +118,9 @@ if (semver.satisfies(pkg.version, '>=0.12')) {
   })
 }
 
-function done (t) {
+function done (t, spanNameSuffix) {
+  spanNameSuffix = spanNameSuffix || 'hello'
+
   return function (data, cb) {
     t.equal(data.transactions.length, 1)
     t.equal(data.spans.length, 1)
@@ -108,7 +130,7 @@ function done (t) {
 
     t.equal(trans.name, 'foo')
     t.equal(trans.type, 'custom')
-    t.equal(span.name, 'GraphQL: hello')
+    t.equal(span.name, 'GraphQL: ' + spanNameSuffix)
     t.equal(span.type, 'db.graphql.execute')
 
     var offset = span.timestamp - trans.timestamp
```

**Comment by dpoetzschke** [comment]
@watson 
thanks for the patch file, i applied this, sqashed my commits and changed the commit message.

i didn't see the commit message requirement in the contribution file and didn't research it.

**Comment by watson** [comment]
Thank you. We should do a better job of listing the commit message rules in CONTRIBUTING.md. I'll make sure we do that.

I can see that my test for some reason doesn't pass on CI. Not sure why it passed locally on my computer - probably related to the specific version of the graphql I had installed. I can just fix it from here if you don't mind 😃 

Good news is that the CLA checker now seems to accept your e-mail address 👍

**Comment by dpoetzschke** [comment]
@watson sure go ahead.

**Comment by watson** [comment]
Released as part of v2.0.6

**Pull request merged**
