### PR TITLE
Initialize config/logger before instrumentation

### LINKED ISSUE #955: Logger is not initialized before usage
**Describe the bug**

When running in AWS Lambda with webpack, the dynamic requires are returning numbers. This, in turn, is causing an attempt to call `this._agent.logger`. Unfortunately, the logger is unavailable and this crashes the request.

**To Reproduce**

1. Webpack bundle a simple import, e.g. with https://github.com/zeit/ncc
2. Import APM agent
3. See crash

**Expected behavior**

Doesn't crash.

**Environment (please complete the following information)**
- OS: [e.g. Linux]
- Node.js version:
- APM Server version:
- Agent version:

**How are you starting the agent? (please tick one of the boxes)**
- [x] Calling `agent.start()` directly (e.g. `require('elastic-apm-node').start(...)`)
- [ ] Requiring `elastic-apm-node/start` from within the source code
- [ ] Starting node with `-r elastic-apm-node/start`

### PR DESCRIPTION
**Pull request by blakeembrey**
Fixes #955.

### Checklist

- [x] Implement code
- [ ] Add tests
- [ ] Update documentation

### CODE REVIEW

**Comment by watson** [comment]
Before I saw that you created this PR, I was playing around with a similar fix locally. I'll paste it here for reference:

```patch
diff --git a/lib/agent.js b/lib/agent.js
index c351bb9..487830c 100644
--- a/lib/agent.js
+++ b/lib/agent.js
@@ -6,6 +6,7 @@ var parseUrl = require('url').parse
 var path = require('path')
 
 var afterAll = require('after-all-results')
+var fallbackLogger = require('console-log-level')()
 var isError = require('core-util-is').isError
 var ancestors = require('require-ancestors')
 var Filters = require('object-filter-sequence')
@@ -47,7 +48,9 @@ function Agent () {
 
 Object.defineProperty(Agent.prototype, 'logger', {
   get () {
-    return this._conf.logger
+    // fall back to simple logger in case we're trying to log before the
+    // configuration have been initialized
+    return this._conf ? this._conf.logger : fallbackLogger
   }
 })
 
```

**Comment by kuisathaverat** [comment]
jenkins run the tests please

**Comment by watson** [comment]
jenkins run the tests please

**Comment by watson** [comment]
jenkins run the tests please

**Comment by watson** [comment]
Thanks for fixing this!

**Comment by watson** [comment]
Now released in v2.9.0

**Pull request merged**
