### PR TITLE
ci(jenkins): debugging got TAV tests

### PR DESCRIPTION
**Pull request by watson**
Please ignore this PR. It's just to debug why the got TAV tests are hanging on Jenkins. See #1673 for details.

### CODE REVIEW

**Comment by watson** [comment]
jenkins run the module tests for got

**Comment by v1v** [comment]
I actually ran the same commands locally and it worked, I wonder if it could be related to the memory allocation for the docker container?

**Comment by watson** [comment]
jenkins run lint please

**Comment by watson** [comment]
jenkins run the module tests for got

**Comment by watson** [comment]
Output of `why-is-node-running` from Jenkins on Node.js 13.11.0:

```
There are 11 handle(s) keeping the process running

# Timeout
./test/instrumentation/modules/http/github-423.js:3 - setTimeout(require('why-is-node-running'), 60 * 1000)

# PIPEWRAP
./node_modules/supports-color/index.js:129 - stdout: getSupportLevel(process.stdout),

# PIPEWRAP
./node_modules/supports-color/index.js:130 - stderr: getSupportLevel(process.stderr)

# DNSCHANNEL
(unknown stack trace)

# TCPSERVERWRAP
./lib/instrumentation/patch-async.js:102             - return original.apply(this, arguments)
./test/instrumentation/modules/http/github-423.js:28 - remote.listen(function () {
./node_modules/tape/lib/test.js:80                   - return val.apply(self, arguments);
./node_modules/tape/lib/test.js:96                   - this._cb(this);
./node_modules/tape/lib/test.js:80                   - return val.apply(self, arguments);
./node_modules/tape/lib/results.js:81                - t.run();
./lib/instrumentation/index.js:309                   - var result = original.apply(this, arguments)

# TCPSERVERWRAP
./lib/instrumentation/patch-async.js:102             - return original.apply(this, arguments)
./test/instrumentation/modules/http/github-423.js:41 - server.listen(function () {
./lib/instrumentation/http-shared.js:64              - return orig.apply(this, arguments)
./lib/instrumentation/index.js:309                   - var result = original.apply(this, arguments)

# TCPWRAP
./lib/instrumentation/patch-async.js:129             - var result = original.apply(this, args)
./lib/instrumentation/patch-async.js:148             - return original.apply(this, arguments)
./lib/instrumentation/http-shared.js:160             - var req = orig.apply(this, newArgs)
./test/instrumentation/modules/http/github-423.js:45 - http.get(url, function (res) {
./lib/instrumentation/http-shared.js:64              - return orig.apply(this, arguments)
./lib/instrumentation/index.js:309                   - var result = original.apply(this, arguments)

# HTTPCLIENTREQUEST
./lib/instrumentation/index.js:309 - var result = original.apply(this, arguments)

# TCPWRAP
(unknown stack trace)

# HTTPINCOMINGMESSAGE
./lib/instrumentation/http-shared.js:64 - return orig.apply(this, arguments)
./lib/instrumentation/index.js:309      - var result = original.apply(this, arguments)

# ZLIB
./test/instrumentation/modules/http/github-423.js:25 - fs.createReadStream(__filename).pipe(zlib.createGzip()).pipe(res)
./lib/instrumentation/http-shared.js:64              - return orig.apply(this, arguments)
```

Output of `why-is-node-running` from my local machine on Node.js 13.11.0:

```
There are 7 handle(s) keeping the process running

# Timeout
./test/instrumentation/modules/http/github-423.js:3 - setTimeout(require('why-is-node-running'), 10 * 1000)

# PIPEWRAP
./node_modules/supports-color/index.js:129 - stdout: getSupportLevel(process.stdout),

# PIPEWRAP
./node_modules/supports-color/index.js:130 - stderr: getSupportLevel(process.stderr)

# DNSCHANNEL
./node_modules/require-in-the-middle/index.js:80         - const exports = self._origRequire.apply(this, arguments)
./node_modules/cacheable-lookup/index.js:2               - const {Resolver, V4MAPPED, ADDRCONFIG} = require('dns');
./node_modules/require-in-the-middle/index.js:80         - const exports = self._origRequire.apply(this, arguments)
./node_modules/got/dist/source/normalize-arguments.js:11 - const cacheable_lookup_1 = require("cacheable-lookup");
./node_modules/require-in-the-middle/index.js:80         - const exports = self._origRequire.apply(this, arguments)
./node_modules/got/dist/source/as-promise.js:8           - const normalize_arguments_1 = require("./normalize-arguments");
./node_modules/require-in-the-middle/index.js:80         - const exports = self._origRequire.apply(this, arguments)
./node_modules/got/dist/source/create.js:4               - const as_promise_1 = require("./as-promise");
./node_modules/require-in-the-middle/index.js:80         - const exports = self._origRequire.apply(this, arguments)
./node_modules/got/dist/source/index.js:7                - const create_1 = require("./create");

# ZLIB
./test/instrumentation/modules/http/github-423.js:25 - fs.createReadStream(__filename).pipe(zlib.createGzip()).pipe(res)
./lib/instrumentation/http-shared.js:64              - return orig.apply(this, arguments)

# ZLIB
./node_modules/decompress-response/index.js:22                 - const decompress = isBrotli ? zlib.createBrotliDecompress() : zlib.createUnzip();
./node_modules/got/dist/source/get-response.js:15              - options.method !== 'HEAD' ? decompressResponse(progressStream) : progressStream);
./node_modules/got/dist/source/request-as-event-emitter.js:121 - await get_response_1.default(typedResponse, options, emitter);
./lib/instrumentation/http-shared.js:181                       - return emit.apply(req, arguments)
./node_modules/@szmarczak/http-timer/dist/source/index.js:39   - return emit(event, ...args);

# ZLIB
./node_modules/elastic-apm-http-client/index.js:100        - return zlib.createGzip()
./node_modules/stream-chopper/index.js:87                  - this._stream = this._transform().once('resume', () => {
./node_modules/stream-chopper/index.js:192                 - this._startStream(() => {
./node_modules/readable-stream/lib/_stream_writable.js:409 - if (state.destroyed) state.onwrite(new ERR_STREAM_DESTROYED('write'));else if (writev) stream._writev(chunk, state.onwrite);else stream._write(chunk, encoding, state.onwrite);
./node_modules/readable-stream/lib/_stream_writable.js:398 - doWrite(stream, state, false, len, chunk, encoding, cb);
./node_modules/readable-stream/lib/_stream_writable.js:307 - ret = writeOrBuffer(this, state, isBuf, chunk, encoding, cb);
./node_modules/elastic-apm-http-client/index.js:282        - this._chopper.write(chunk, cb)
./node_modules/elastic-apm-http-client/index.js:253        - this._writevCleaned(objs, cb)
./node_modules/elastic-apm-http-client/index.js:271        - processBatch()
./node_modules/readable-stream/lib/_stream_writable.js:409 - if (state.destroyed) state.onwrite(new ERR_STREAM_DESTROYED('write'));else if (writev) stream._writev(chunk, state.onwrite);else stream._write(chunk, encoding, state.onwrite);
./node_modules/readable-stream/lib/_stream_writable.js:505 - doWrite(stream, state, true, state.length, buffer, '', holder.finish); // doWrite is almost always async, defer these to save a bit of time
./node_modules/readable-stream/lib/_stream_writable.js:321 - if (!state.writing && !state.corked && !state.bufferProcessing && state.bufferedRequest) clearBuffer(this, state);
./node_modules/elastic-apm-http-client/index.js:302        - this.uncork()
```

**Comment by watson** [comment]
jenkins run the module tests for got

**Comment by astorm** [comment]
@watson doing some cleanup/triage -- is this a PR you anticipate needing in the future, or can we close it out?

**Comment by watson** [comment]
@astorm nope - I'll close it 👍

**Pull request closed without merging**
