### PR TITLE
3.39.0

### PR DESCRIPTION
**Pull request by trentm**
It has been over a month since the 3.38.0 release. There are a lot of good changes to get out (including many of the issues on the 8.5 milestone).

### CODE REVIEW

**Review by astorm — APPROVED** [review]
👍 game for a release

**Comment by trentm** [comment]
tagged

**Comment by trentm** [comment]
https://apm-ci.elastic.co/job/apm-agent-nodejs/job/apm-agent-nodejs-mbp/view/tags/job/v3.39.0/

**Comment by trentm** [comment]
- release notes (in a bit): https://www.elastic.co/guide/en/apm/agent/nodejs/current/release-notes-3.x.html#release-notes-3.39.0
- release (with Lambda ARN table): https://github.com/elastic/apm-agent-nodejs/releases/tag/v3.39.0
- npm release: https://www.npmjs.com/package/elastic-apm-node/v/3.39.0

**Pull request merged**
