### PR TITLE
chore(package): bump 'standard' linter to ^14.3.1

### PR DESCRIPTION
**Pull request by watson**
Also fix the linting errors related to the new linting rules in this new version.

### CODE REVIEW

**Comment by Qard** [comment]
This appears to result in syntax errors on old versions of Node.js.

**Comment by watson** [comment]
This is a bug in standard. I'll fix it

**Comment by watson** [comment]
Hmm seems like standard v14.3.1 hasn't actually been released yet... investigating...

**Comment by watson** [comment]
14.3.1 has been released now

**Pull request merged**
