### PR TITLE
[chore] Raise test timeout from 3h to 4h

### PR DESCRIPTION
**Pull request by cachedout**
The master branch of this project is currently [failing due to it reaching a configured timeout of 3hr](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-nodejs%2Fapm-agent-nodejs-mbp/detail/master/1003/pipeline). 

This PR raises that timeout to 4hr to hopefully give the pipeline enough time to complete.

### Checklist

- [x] Implement code

### CODE REVIEW

**Review by mdelapenya — APPROVED** [review]

**Review by v1v — APPROVED** [review]

**Review by trentm — CHANGES_REQUESTED** [review]
No, thanks. There is nothing in the test suite that should be approaching this time. Earlier passing runs (e.g. https://apm-ci.elastic.co/job/apm-agent-nodejs/job/apm-agent-nodejs-mbp/job/master/997/) show that a complete full run (including the approximately 1h for the "TAV Tests" stage) should be about 1.5h.

**Comment by trentm** [comment]
My guess is there is some new hang in the tests. E.g. looking at the "Test / Node.js-10" stage

- blue ocean page: https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-nodejs%2Fapm-agent-nodejs-mbp/detail/master/1003/pipeline/164
- complete log: https://apm-ci.elastic.co/blue/rest/organizations/jenkins/pipelines/apm-agent-nodejs/pipelines/apm-agent-nodejs-mbp/branches/master/runs/1003/nodes/164/steps/407/log/?start=0

The log ends with:

```
[2021-08-04T05:56:21.405Z] node_tests_1     | running (cwd: ./): node --require /app/test/_promise_rejection.js test/instrumentation/modules/mongodb.test.js
[2021-08-04T05:56:23.939Z] node_tests_1     | TAP version 13
[2021-08-04T05:56:23.940Z] node_tests_1     | # instrument simple command
[2021-08-04T05:56:23.940Z] node_tests_1     | ok 1 no connect error
[2021-08-04T05:56:23.940Z] node_tests_1     | ok 2 got a valid server connection
[2021-08-04T05:56:24.198Z] node_tests_1     | ok 3 no insert error
[2021-08-04T05:56:24.198Z] node_tests_1     | ok 4 inserted three records
[2021-08-04T05:56:24.198Z] node_tests_1     | ok 5 no update error
[2021-08-04T05:56:24.198Z] node_tests_1     | ok 6 updated one record
[2021-08-04T05:56:24.198Z] node_tests_1     | ok 7 no delete error
[2021-08-04T05:56:24.198Z] node_tests_1     | ok 8 deleted one record
[2021-08-04T05:56:24.198Z] node_tests_1     | ok 9 no cursor next error
[2021-08-04T05:56:24.198Z] node_tests_1     | ok 10 found record #2
[2021-08-04T05:56:24.198Z] node_tests_1     | ok 11 no cursor next error
[2021-08-04T05:56:24.198Z] node_tests_1     | ok 12 found record #3
[2021-08-04T05:56:24.198Z] node_tests_1     | ok 13 transaction name is "foo"
[2021-08-04T05:56:24.198Z] node_tests_1     | ok 14 transaction type is "bar"
[2021-08-04T05:56:24.198Z] node_tests_1     | ok 15 transaction result is "success"
[2021-08-04T08:14:20.024Z] Cannot contact apm-ci-immutable-ubuntu-1804-1628056136616325348: java.lang.InterruptedException
[2021-08-04T08:49:11.021Z] Could not connect to apm-ci-immutable-ubuntu-1804-1628056136616325348 to send interrupt signal to process
```

Comparing to build 997, an earlier successful run:

```
...
[2021-07-30T05:56:42.415Z] node_tests_1     | running (cwd: ./): node --require /app/test/_promise_rejection.js test/instrumentation/modules/mongodb.test.js
[2021-07-30T05:56:45.724Z] node_tests_1     | TAP version 13
[2021-07-30T05:56:45.724Z] node_tests_1     | # instrument simple command
[2021-07-30T05:56:45.724Z] node_tests_1     | ok 1 no connect error
[2021-07-30T05:56:45.724Z] node_tests_1     | ok 2 got a valid server connection
[2021-07-30T05:56:45.724Z] node_tests_1     | (node:603) [MONGODB DRIVER] Warning: Top-level use of w, wtimeout, j, and fsync is deprecated. Use writeConcern instead.
[2021-07-30T05:56:45.724Z] node_tests_1     | ok 3 no insert error
[2021-07-30T05:56:45.724Z] node_tests_1     | ok 4 inserted three records
[2021-07-30T05:56:45.724Z] node_tests_1     | ok 5 found valid span
[2021-07-30T05:56:45.724Z] node_tests_1     | ok 6 span name is "elasticapm.test.insert"
[2021-07-30T05:56:45.724Z] node_tests_1     | ok 7 span type is "db"
[2021-07-30T05:56:45.724Z] node_tests_1     | ok 8 span subtype is "mongodb"
[2021-07-30T05:56:45.724Z] node_tests_1     | ok 9 span action is "query"
[2021-07-30T05:56:45.724Z] node_tests_1     | ok 10 context.destination.address is defined
[2021-07-30T05:56:45.724Z] node_tests_1     | ok 11 span.context.destination
[2021-07-30T05:56:45.724Z] node_tests_1     | ok 12 no update error
[2021-07-30T05:56:45.724Z] node_tests_1     | ok 13 updated one record
[2021-07-30T05:56:45.724Z] node_tests_1     | ok 14 found valid span
[2021-07-30T05:56:45.724Z] node_tests_1     | ok 15 span name is "elasticapm.test.update"
[2021-07-30T05:56:45.724Z] node_tests_1     | ok 16 span type is "db"
[2021-07-30T05:56:45.724Z] node_tests_1     | ok 17 span subtype is "mongodb"
[2021-07-30T05:56:45.725Z] node_tests_1     | ok 18 span action is "query"
[2021-07-30T05:56:45.725Z] node_tests_1     | ok 19 context.destination.address is defined
[2021-07-30T05:56:45.725Z] node_tests_1     | ok 20 span.context.destination
[2021-07-30T05:56:45.725Z] node_tests_1     | ok 21 no delete error
[2021-07-30T05:56:45.725Z] node_tests_1     | ok 22 deleted one record
[2021-07-30T05:56:45.725Z] node_tests_1     | ok 23 found valid span
[2021-07-30T05:56:45.725Z] node_tests_1     | ok 24 span name is "elasticapm.test.delete"
[2021-07-30T05:56:45.725Z] node_tests_1     | ok 25 span type is "db"
[2021-07-30T05:56:45.725Z] node_tests_1     | ok 26 span subtype is "mongodb"
[2021-07-30T05:56:45.725Z] node_tests_1     | ok 27 span action is "query"
[2021-07-30T05:56:45.725Z] node_tests_1     | ok 28 context.destination.address is defined
[2021-07-30T05:56:45.725Z] node_tests_1     | ok 29 span.context.destination
[2021-07-30T05:56:45.725Z] node_tests_1     | ok 30 no cursor next error
[2021-07-30T05:56:45.725Z] node_tests_1     | ok 31 found record #2
[2021-07-30T05:56:45.725Z] node_tests_1     | ok 32 no cursor next error
[2021-07-30T05:56:45.725Z] node_tests_1     | ok 33 found record #3
[2021-07-30T05:56:45.725Z] node_tests_1     | ok 34 transaction name is "foo"
[2021-07-30T05:56:45.725Z] node_tests_1     | ok 35 transaction type is "bar"
[2021-07-30T05:56:45.725Z] node_tests_1     | ok 36 transaction result is "success"
[2021-07-30T05:56:45.725Z] node_tests_1     | ok 37 found valid span
[2021-07-30T05:56:45.725Z] node_tests_1     | ok 38 span name is "elasticapm.test.find"
[2021-07-30T05:56:45.725Z] node_tests_1     | ok 39 span type is "db"
[2021-07-30T05:56:45.725Z] node_tests_1     | ok 40 span subtype is "mongodb"
[2021-07-30T05:56:45.725Z] node_tests_1     | ok 41 span action is "query"
[2021-07-30T05:56:45.725Z] node_tests_1     | ok 42 context.destination.address is defined
[2021-07-30T05:56:45.725Z] node_tests_1     | ok 43 span.context.destination
[2021-07-30T05:56:45.725Z] node_tests_1     | 
[2021-07-30T05:56:45.725Z] node_tests_1     | 1..43
[2021-07-30T05:56:45.725Z] node_tests_1     | # tests 43
[2021-07-30T05:56:45.725Z] node_tests_1     | # pass  43
[2021-07-30T05:56:45.725Z] node_tests_1     | 
[2021-07-30T05:56:45.725Z] node_tests_1     | # ok
[2021-07-30T05:56:45.725Z] node_tests_1     | 
[2021-07-30T05:56:45.725Z] node_tests_1     | running (cwd: ./): node --require /app/test/_promise_rejection.js test/instrumentation/modules/pug.test.js
...
```

The order of TAP test assertions start to diverge after "ok 4 inserted three records". I'll try to repro.

**Comment by trentm** [comment]
Also, that the hang is (potentially) in the mongodb test makes this recent commit look suspicious:

```
Date:   2021-07-30T10:28:10-07:00 (5 days ago)

    fix: adds supports for MongoDB 4.0+ (#2171)

    * feat: Adds support for 4.x branch of mongodb driver

    Fixes https://github.com/elastic/apm-agent-nodejs/pull/2170
```

**Comment by trentm** [comment]
> I'll try to repro.

Yes, I was able to repro.

```
% node --version
v12.22.1

% git status
On branch master
Your branch is up to date with 'origin/master'.

% .ci/scripts/test.sh -b "release" -t "" "10"
Running Agent tests with node v10 (BUILD_TYPE=release, FORCE=false)
...
node_tests_1     |
node_tests_1     | running (cwd: ./): node --require /app/test/_promise_rejection.js test/instrumentation/modules/mongodb.test.js
node_tests_1     | {"log.level":"error","@timestamp":"2021-08-04T15:37:43.844Z","log":{"logger":"elastic-apm-node"},"ecs":{"version":"1.6.0"},"message":"metadata requests did not finish, possible deadlock"}
node_tests_1     | TAP version 13
node_tests_1     | # instrument simple command
node_tests_1     | ok 1 no connect error
node_tests_1     | ok 2 got a valid server connection
node_tests_1     | ok 3 no insert error
node_tests_1     | ok 4 inserted three records
node_tests_1     | ok 5 no update error
node_tests_1     | ok 6 updated one record
node_tests_1     | ok 7 no delete error
node_tests_1     | ok 8 deleted one record
node_tests_1     | ok 9 no cursor next error
node_tests_1     | ok 10 found record #2
node_tests_1     | ok 11 no cursor next error
node_tests_1     | ok 12 found record #3
node_tests_1     | ok 13 transaction name is "foo"
node_tests_1     | ok 14 transaction type is "bar"
node_tests_1     | ok 15 transaction result is "success"
```

My test run is hung there.

I'll open a separate issue with the details here so far, and close this PR.

**Comment by cachedout** [comment]
Sounds good. Thanks, @trentm

**Comment by trentm** [comment]
I've opened https://github.com/elastic/apm-agent-nodejs/issues/2177 for the mongodb test hang. Close this in favour of that issue.

**Pull request closed without merging**
