### PR TITLE
fix: Express route calc when next(err-that-is-not-Error-instance) is used

### PR DESCRIPTION
**Pull request by trentm**
Express considers any value passed to a handler's next() handler
to be an error, except the special case 'route' and 'router' strings.
Before this change the agent's Express route handling (used for setting
transaction.name) would only consider the arg to be an error if
`instanceof Error`.

Refs: #2741

### CODE REVIEW

**Comment by trentm** [comment]
If it helps, here is an Express server that plays with routing cases to explore how routing works and how our transaction.name calculation works:

```js
const apm = require('./').start({ // elastic-apm-node
  serviceName: 'play-express-next-values',
  metricsInterval: '0s',
  centralConfig: false,
  cloudProvider: 'none'
})
apm.addTransactionFilter(trans => {
  console.log('-- transaction.name="%s"', trans.name)
  return trans
})

const express = require('express')

const app = express()

const apiRouter = express.Router()
apiRouter.get('/foo',
  function fooHandler1 (req, res, next) {
    console.log('[fooHandler1] query', req.query)
    if (req.query.next === 'route') {
      // This skips over `fooHandler2`, to the next matching route, if any.
      next('route')
    } else if (req.query.next === 'router') {
      // This skips out of the whole router.
      next('router')
    } else {
      next()
    }
  },
  function fooHandler2 (req, res, next) {
    console.log('[fooHandler2]')
    res.send('response from foo')
  })
apiRouter.get('/boom', function boomHandler (req, res, next) {
  throw new Error('boom')
})
apiRouter.get('/weird', function weirdHandler (req, res, next) {
  // This passes a "weird" value to `next()`. Weird in that it is not an Error
  // instance or either of the special case "route" or "router" values that
  // Express accepts.
  next({ weird: true })
})
apiRouter.use(function apiMiddleware (req, res, next) {
  console.log('[apiMiddleware]')
  next()
})
apiRouter.use(function apiErrHandler (err, req, res, next) {
  console.log('[apiErrHandler] err=%s', err.message || err)
  res.status(500)
    .send('there was an API error: ' + err)
})

app.use('/top', function topHandler (req, res, next) {
  console.log('[topHandler]')
  res.send('response from top-level')
})
app.use('/api', apiRouter)
app.use(function topLevelMiddleware (req, res, next) {
  console.log('[topLevelMiddleware]')
  next()
})
app.get('/:any/foo', function weirdTopLevelAnyFooHandler (req, res, next) {
  console.log('[weirdTopLevelAnyFooHandler]')
  res.send('response from weirdTopLevelAnyFooHandler')
})
app.use(function appErrHandler (err, req, res, next) {
  console.log('[appErrHandler] err=%s', err.message || err)
  res.status(500)
    .send('there was an error: ' + err)
})

app.listen(3000, () => console.log('server running on port 3000'))
```

If you run that and then call its `/api/weird` endpoint (`curl -i localhost:3000/api/weird`), you get:

```
% node play-express-next-values.js
server running on port 3000
[apiErrHandler] err={ weird: true }
-- transaction.name="GET /api/weird"
```

Before the fix in this PR the transaction.name set by the APM agent was "GET /weird" because the `/api` part was incorrectly popped from `req[symbols.expressMountStack]`.

**Comment by trentm** [comment]
Note that this drops the `req.router` guard that was in the previous code. That was added in https://github.com/elastic/apm-agent-nodejs/pull/938 (to fix https://github.com/elastic/apm-agent-nodejs/issues/935), but I don't know why that guard. It wasn't discussed on the issue or PR.

AFAICT Express (for all versions that we currently support: 4.0.0 ... 4.18.1) the `Route.prototype.dispatch` method has always set `req.router`, e.g. https://github.com/expressjs/express/blob/4.18.1/lib/router/route.js#L112  The full TAV tests are passing.

**Comment by trentm** [comment]
run module tests for express

**Review by astorm — APPROVED** [review]
Fix looks good and look like is results in more correct behavior.  Approving.  

Since we are changing a long standing (if incorrect) behavior this might be worth calling out explicitly in the changelog so users and support folks can find it.

**Comment by trentm** [comment]
> Since we are changing a long standing (if incorrect) behavior this might be worth calling out explicitly in the changelog

:+1:

**Pull request merged**
