### PR TITLE
fix: adapt logger.child call to new pino 6 format

### LINKED ISSUE #2332: pino 6 issue
**Describe the bug**

Providing a custom pino logger to apm causes this deprecation warning like so:
```
(node:3318) [PINODEP004] PinoWarning: bindings.serializers is deprecated, use options.serializers option instead
    at Object.emit (./node_modules/fastify-warning/index.js:52:13)
    at Pino.child (./node_modules/pino/lib/proto.js:91:13)
    at Object.createLogger (./node_modules/elastic-apm-node/lib/logging.js:119:27)
    at new Config (./node_modules/elastic-apm-node/lib/config.js:268:27)
    at config (./node_modules/elastic-apm-node/lib/config.js:230:10)
    at Agent._config (./node_modules/elastic-apm-node/lib/agent.js:184:16)
    at Agent.start (./node_modules/elastic-apm-node/lib/agent.js:205:8)
    at run (./index.js:16:43)
    at Object.<anonymous> (./index.js:96:1)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
```

**To Reproduce**

Steps to reproduce the behavior: 
1. Provide a pino 6 logger to apm
2. Start APM

**Expected behavior**

No deprecation warning

**Environment (please complete the following information)**

- OS: [e.g. Linux] Linux
- Node.js version: 14
- APM Server version: irrelevant
- Agent version: 3.21.0

**How are you starting the agent? (please tick one of the boxes)**

- [X] Calling `agent.start()` directly (e.g. `require('elastic-apm-node').start(...)`)
- [ ] Requiring `elastic-apm-node/start` from within the source code
- [ ] Starting node with `-r elastic-apm-node/start`

**Additional context**

I'm going to shorten the full config details as I think it's irrelevant as well. I'm preparing a PR.

- Agent config options 
  <details>
    <summary>Click to expand</summary>

    ```
    const appLogger = pino({ ..., serializers, ... });
    ...
    apm.start({ ...
      logger: appLogger
    ...
    })
    ```
  </details>
- `package.json` dependencies:
  <details>
    <summary>Click to expand</summary>

    ```
    "elastic-apm-node": "^3.21.0",
    "pino": "^6.13.2",
    ```
  </details>

### PR DESCRIPTION
**Pull request by Marsup**
Fixes #2332.

To avoid a breaking, I thought it was better not to assume pino's logger was using version 6.
Do you think it requires additional tests?

### Checklist

- [x] Implement code
- [x] Add CHANGELOG.asciidoc entry
- [x] Commit message follows [commit guidelines](https://github.com/elastic/apm-agent-nodejs/blob/master/CONTRIBUTING.md#commit-message-guidelines)

### CODE REVIEW

**Review by trentm — DISMISSED** [review]
Approving to run tests. I suspect there will be a conflict on the CHANGELOG file to sort out (but that can be done afterwards).

**Comment by Marsup** [comment]
Done :heavy_check_mark: 

I'm wondering something before merging, should `serializers` be a shorthand property or should it stick to pre-ES6 compat like a couple lines below?

**Comment by trentm** [comment]
> I'm wondering something before merging, should `serializers` be a shorthand property or should it stick to pre-ES6 compat like a couple lines below?

https://node.green/#ES2015-syntax-object-literal-extensions-shorthand-properties says shorthand properties were in Node v4.x and our base supported node version is v8.6.0 (https://github.com/elastic/apm-agent-nodejs/blob/master/package.json#L45-L47) so using the shorthand syntax is good.

**Review by trentm — APPROVED** [review]

**Comment by trentm** [comment]
@elasticmachine, run elasticsearch-ci/docs

**Comment by trentm** [comment]
Thanks!

**Pull request merged**
