### PR TITLE
chore(*): only list Node versions in 'engines' field that we support

### PR DESCRIPTION
**Pull request by watson**
As of now the old and the new version of this field is the same, but when 10.x is released we don't want that to be covered as well.

### CODE REVIEW

**Comment by Qard** [comment]
Is there any cases where this would prevent install on 10.x? Is that intended? Last I checked, npm itself only uses engines as an advisory field, but other tools may not. I know heroku uses it to control what version of Node.js to install on a server.

**Comment by watson** [comment]
It should just print out a warning if you run it on a unsupported version. I haven't heard of any scenario where it will block you from running it.

**Comment by watson** [comment]
We should obviously bump this together with the other files we bump when a new version is released, e.g. `.travis.yml` etc

**Comment by watson** [comment]
Btw, I'm just saw that AppVeyor is trying to run even though there's no `appveyer.yml` in the branch. I thought I had disabled this, but seems I forgot to press save. So just ignore that failure.

**Pull request merged**
