### PR TITLE
feat(fastify): add captureBody support

### PR DESCRIPTION
**Pull request by xxzefgh**
Closes: #1906
Closes: #3217

### CODE REVIEW

**Comment by xxzefgh** [comment]
have not tested this yet, will reopen later

**Comment by xxzefgh** [comment]
Tested with `fastify@3.28.0`,  `http.request.body.original` field is populated with request body

**Comment by trentm** [comment]
run module tests for fastify

**Comment by xxzefgh** [comment]
Hi @trentm, I've added tests as you requested. One issue is that tests are run against v2 (required in devDependencies), which was already supported. I did locally install v3 and it passed, but I'm not sure how tests can be run against multiple versions.

**Review by trentm — APPROVED** [review]

**Comment by trentm** [comment]
@xxzefgh Thanks!

> One issue is that tests are run against v2 (required in devDependencies), which was already supported. I did locally install v3 and it passed, but I'm not sure how tests can be run against multiple versions.

We *just* recently updated devDeps to fastify@3 in #2738

However, we also use [test-all-versions](https://github.com/watson/test-all-versions) (TAV for short) to test all/most supported versions of modules that we instrument. https://github.com/elastic/apm-agent-nodejs/blob/7e9b9e31d20c5170854ac62319bea6818ba2a81c/.tav.yml#L475-L500 is the current block that defines the fastify versions we test against.  I'll kick off those "TAV" tests for this PR after the regular tests run.

**Comment by xxzefgh** [comment]
Ok, I think I was wrong on v2 comment, as I forgot to comment out my patches for v2 before testing 😐

Rebased and added changes to `.tav.yml`

**Comment by trentm** [comment]
I'm not yet sure what is going on with the `node test/instrumentation/modules/fastify/fastify.test.js` test failure with node 8.6 (in the GitHub Actions-based test above). I cannot reproduce that failure using node 8.6 on my mac. I'll take a look later when I have a chance.

**Comment by trentm** [comment]
Ah, yes, I can reproduce locally: this happens when using fastify@3 (now in our package-lock.json file) and node 8.6. Fastify@3 only supports node v10 and later.  So, we need to add a guard on top of the relevant fastify test files to just skip the test if the node version and fastify version aren't supported.

@xxzefgh Can you please add this patch to your PR:

```
diff --git a/test/instrumentation/modules/fastify/fastify.test.js b/test/instrumentation/modules/fastify/fastify.test.js
index f9f294ab..ae343585 100644
--- a/test/instrumentation/modules/fastify/fastify.test.js
+++ b/test/instrumentation/modules/fastify/fastify.test.js
@@ -8,6 +8,17 @@ const agent = require('../../../..').start({
   captureBody: 'all'
 })

+const fastifyVer = require('../../../../node_modules/fastify/package.json').version
+const semver = require('semver')
+if (
+  (semver.satisfies(fastifyVer, '1.x') && !semver.satisfies(process.version, '>=6 <12')) ||
+  (semver.satisfies(fastifyVer, '2.x') && !semver.satisfies(process.version, '>=6 <15')) ||
+  (semver.satisfies(fastifyVer, '3.x') && !semver.satisfies(process.version, '>=10'))
+) {
+  console.log(`# SKIP fastify@${fastifyVer} does not support node ${process.version}`)
+  process.exit()
+}
+
 const http = require('http')

 const Fastify = require('fastify')
 ```

**Comment by trentm** [comment]
run module tests for fastify

**Comment by trentm** [comment]
@elasticmachine, run elasticsearch-ci/docs

**Comment by trentm** [comment]
The "test all versions" tests failed on the `captureBody` test with fastify@1 and node@10. For some reason that I didn't dig into, the `preHandler` life-cycle hook doesn't run with fastify@1 (though the hook is listed at https://github.com/fastify/fastify/blob/1.x/docs/Lifecycle.md). However, fastify@1 is long since EOL, so we don't need to support new features for it.  Here is a suggested patch for skipping that test for this combination (and a couple other doc tweaks):

```diff
diff --git a/docs/supported-technologies.asciidoc b/docs/supported-technologies.asciidoc
index b961ccfc..6b0b684c 100644
--- a/docs/supported-technologies.asciidoc
+++ b/docs/supported-technologies.asciidoc
@@ -46,7 +46,7 @@ These are the frameworks that we officially support:
 router information for full support. We currently support the most popular Koa router called
 https://github.com/alexmingoia/koa-router[koa-router].
 |<<restify,Restify>> |>=5.2.0
-|<<fastify,Fastify>> |>=1.0.0; see also https://www.fastify.io/docs/latest/LTS/[Fastify's own LTS documentation]
+|<<fastify,Fastify>> |>=1.0.0; see also https://www.fastify.io/docs/latest/Reference/LTS/[Fastify's own LTS documentation]
 |<<lambda,AWS Lambda>> |N/A
 |=======================================================================
 
diff --git a/lib/instrumentation/modules/fastify.js b/lib/instrumentation/modules/fastify.js
index 7646822e..cd757ca7 100644
--- a/lib/instrumentation/modules/fastify.js
+++ b/lib/instrumentation/modules/fastify.js
@@ -61,6 +61,7 @@ module.exports = function (fastify, agent, { version, enabled }) {
     })
 
     // Save the parsed req body to be picked up by getContextFromRequest().
+    // (This doesn't work for fastify@1, but that is now EOL.)
     _fastify.addHook('preHandler', (req, reply, next) => {
       req.raw.body = req.body
       next()
diff --git a/test/instrumentation/modules/fastify/fastify.test.js b/test/instrumentation/modules/fastify/fastify.test.js
index ae343585..df05c5bb 100644
--- a/test/instrumentation/modules/fastify/fastify.test.js
+++ b/test/instrumentation/modules/fastify/fastify.test.js
@@ -65,55 +65,58 @@ test('transaction name', function (t) {
   })
 })
 
-test('captureBody', function (t) {
-  t.plan(9)
-
-  const postData = JSON.stringify({ foo: 'bar' })
-
-  resetAgent(data => {
-    assert(t, data, { name: 'POST /postSomeData', method: 'POST' })
-    t.equal(data.transactions[0].context.request.body, postData,
-      'body was captured to trans.context.request.body')
-    fastify.close()
-  })
-
-  var fastify = Fastify()
+// Fastify `captureBody` support is only supported for fastify@2.x and later.
+if (semver.gte(fastifyVer, '2.0.0')) {
+  test('captureBody', function (t) {
+    t.plan(9)
+
+    const postData = JSON.stringify({ foo: 'bar' })
+
+    resetAgent(data => {
+      assert(t, data, { name: 'POST /postSomeData', method: 'POST' })
+      t.equal(data.transactions[0].context.request.body, postData,
+        'body was captured to trans.context.request.body')
+      fastify.close()
+    })
 
-  fastify.post('/postSomeData', (request, reply) => {
-    reply.send('your data has been posted')
-  })
+    var fastify = Fastify()
 
-  fastify.listen(0, function (err) {
-    t.error(err)
+    fastify.post('/postSomeData', (request, reply) => {
+      reply.send('your data has been posted')
+    })
 
-    // build the URL manually as older versions of fastify doesn't supply it as
-    // an argument to the callback
-    const port = fastify.server.address().port
-    const cReq = http.request(
-      'http://localhost:' + port + '/postSomeData',
-      {
-        method: 'POST',
-        hostname: 'localhost',
-        port,
-        headers: {
-          'Content-Type': 'application/json',
-          'Content-Length': Buffer.byteLength(postData)
+    fastify.listen(0, function (err) {
+      t.error(err)
+
+      // build the URL manually as older versions of fastify doesn't supply it as
+      // an argument to the callback
+      const port = fastify.server.address().port
+      const cReq = http.request(
+        'http://localhost:' + port + '/postSomeData',
+        {
+          method: 'POST',
+          hostname: 'localhost',
+          port,
+          headers: {
+            'Content-Type': 'application/json',
+            'Content-Length': Buffer.byteLength(postData)
+          }
+        },
+        function (res) {
+          t.strictEqual(res.statusCode, 200)
+          res.on('data', function (chunk) {
+            t.strictEqual(chunk.toString(), 'your data has been posted')
+          })
+          res.on('end', function () {
+            agent.flush()
+          })
         }
-      },
-      function (res) {
-        t.strictEqual(res.statusCode, 200)
-        res.on('data', function (chunk) {
-          t.strictEqual(chunk.toString(), 'your data has been posted')
-        })
-        res.on('end', function () {
-          agent.flush()
-        })
-      }
-    )
-    cReq.write(postData)
-    cReq.end()
+      )
+      cReq.write(postData)
+      cReq.end()
+    })
   })
-})
+}
 
 function resetAgent (cb) {
   agent._instrumentation.testReset()
```

@xxzefgh If you are good adding that to your PR, I can re-run the tests. Thanks for persisting through the slog of testing.

**Comment by trentm** [comment]
@elasticmachine, run elasticsearch-ci/docs

**Comment by trentm** [comment]
run module tests for fastify

**Comment by trentm** [comment]
This has languished. I'm adding some small commits to get this over the line.

**Comment by trentm** [comment]
@elasticmachine, run elasticsearch-ci/docs

**Comment by trentm** [comment]
@elasticmachine, run elasticsearch-ci/docs

**Comment by trentm** [comment]
@elasticmachine, run elasticsearch-ci/docs

**Pull request merged**
