### PR TITLE
fix: ensure correct run context for 'mongodb' instrumentation

### PR DESCRIPTION
**Pull request by trentm**
Also:
- Fix an issue where instrumentation of `new MongoClient(url)` would
  fail because the internal handling of `arguments` would add
  `arguments[1]` but arguments.length stayed at 1. Fix by first
  changing to an Array.
- Fix instrument of a connection made using the MongoClient.connect
  static method. #2467

Refs: #2430 
Fixes: #2467

### Checklist

- [x] Whoa, we aren't running TAV=mongodb in Jenkins. Why is that?
- [x] Implement code
- [x] Add tests
- [x] Pass TAV tests. Still getting `.end() already called` error in Jenkins.
- [x] Add CHANGELOG.asciidoc entry

### CODE REVIEW

**Comment by trentm** [comment]
run module tests for mongodb

**Comment by trentm** [comment]
run module tests for mongodb

**Comment by trentm** [comment]
run module tests for mongodb

**Comment by trentm** [comment]
run module tests for mongodb

**Comment by trentm** [comment]
Getting test failures in Jenkins CI with TAV tests. At least one of the errors is with `mongodb@4.0.1`.

**Comment by trentm** [comment]
run module tests for mongodb

**Comment by trentm** [comment]
run module tests for mongodb

**Review by astorm — APPROVED** [review]

**Pull request merged**
