### PR TITLE
feat(debug): initiate debugging on trace

### LINKED ISSUE #961: Change DEBUG=true to logLevel: 'trace'
To output the agent config today, you have to both set the config `logLevel: 'debug'` (or `'trace'`) and the environment variable `DEBUG=true`. It would be easier if you just had to set `logLevel: 'trace'`.

The reason why we went with the `DEBUG` environment variable originally was that it was easy to detect, so that [the entire code block](https://github.com/elastic/apm-agent-nodejs/blob/e1026382d8c6987137c00ffda83eb4e1acf292e6/lib/agent.js#L138-L161) could be skipped if it wasn't needed. But it's just too complicated of an API. Instead the if-statement should just check if `logLevel === 'trace'`

### PR DESCRIPTION
**Pull request by curtisjohnson1**
fixes #961 

### Checklist

- [x] Implement code
- [ ] Add tests
- [x] Update documentation

### CODE REVIEW

**Comment by curtisjohnson1** [comment]
No problem. I can do that

**Comment by curtisjohnson1** [comment]
I've fixed the logger issue you mentioned, although it's squashed that commit into my original one. Apologies about that

**Comment by watson** [comment]
jenkins run the test please

**Comment by watson** [comment]
jenkins run the tests please

**Comment by watson** [comment]
Thanks for your help 🥇 

I've just published a new version of the agent to npm with your commit

**Pull request merged**
