### PR TITLE
Force Trusty distribution instead of relying on default

### PR DESCRIPTION
**Pull request by cotsog**
See https://blog.travis-ci.com/2019-04-15-xenial-default-build-environment

### CODE REVIEW

**Comment by watson** [comment]
Wow, thanks for the quick PR ❤️

**Comment by watson** [comment]
Possibly `sudo: required` doesn't do any difference anymore, but if removing it, we should also remove the above comment. So, for now, I'll just leave it in. Will look into if it can be removed in another PR

**Comment by watson** [comment]
All looks good now 👍 I'll fix the commit message linting error during "Squash and merge".

Thanks again for the quick help 💯

**Comment by Qard** [comment]
We should probably also test if xenial works and maybe just switch to that. Trusty is _ancient_ at this point. 😅

**Comment by watson** [comment]
Travis unfortunately doesn't support Cassandra on Xenial yet, and hence our tests fails when they run on Xenial - which is what just happened as we were rolled over automatically from Trusty to Xenial a few hours ago

**Pull request merged**
