### PR TITLE
Closes #1834 fix: Treat set-cookie in response headers as sensitive data

### LINKED ISSUE #1834: Auto filter sensitive header set-cookie not filtered for response headers
**Describe the bug**

When filterHttpHeaders is set to true (ELASTIC_APM_FILTER_HTTP_HEADERS) it's expected to redact sensitive cookie and set-cookie information from the request and response headers. This is done in http-headers.js but only the request headers and not the response headers is getting filtered. This is mainly an issue for the set-cookie in the response header.

**To Reproduce**

1. Setup the APM and set ELASTIC_APM_FILTER_HTTP_HEADERS to true (Should be true by default)
2. Do a call that have a set-cookie with a sensitive value in the response. Ex. A login request
3. Check the APM logs and check the response headers and the set-cookie shows up in clear text.

**Expected behavior**

The expected behavior is that the headers with sensitive values should be masked by the string [REDACTED]. Right now to check what is a sensitive value the node package [is-secret](https://www.npmjs.com/package/is-secret) is used. It's a good starting point but to help this along it would be desirable to be able to set additional headers and cookies that contains sensitive information.

Something like this as environment variable could be a solution:

- ELASTIC_APM_SENSETIVE_HTTP_HEADERS = auth,secreat
- ELASTIC_APM_SENSETIVE_HTTP_COOKIES = auth,private_token

**Environment (please complete the following information)**

- OS: OSX
- Node.js version: 12.18.3
- APM Server version: 7.9.2
- Agent version: 3.4.0

**How are you starting the agent? (please tick one of the boxes)**

- [X] Calling `agent.start()` directly (e.g. `require('elastic-apm-node').start(...)`)
- [ ] Requiring `elastic-apm-node/start` from within the source code
- [ ] Starting node with `-r elastic-apm-node/start`

### PR DESCRIPTION
**Pull request by StoraH**
Re-submission of https://github.com/elastic/apm-agent-nodejs/pull/1835

### CODE REVIEW

**Comment by astorm** [comment]
jenkins run the tests please

**Comment by astorm** [comment]
jenkins run the tests please

**Comment by astorm** [comment]
Thanks for the re-submission @StoraH -- it looks like one of our internal CI jobs is hanging.  I'm working with a team here to get that sorted out.  Once we do that, we should be to accept.  Thanks again for finding the bug, making the PR, and jumping through the hoops to get this submitted :)

**Comment by astorm** [comment]
@StoraH I'm not sure if something changed in the branch or if I missed this the first time around, but I saw some odd behavior with your test in my final "pre-merge" manual testing and wanted to get your opinion on it. 

If I take your [`test/filters.js`](https://github.com/elastic/apm-agent-nodejs/blob/aa6b91ff97a9d601a23f998b8b9ef772c224d056/test/filters.js) file, and run it against the _master_ branch -- it doesn't produce a failure.  I would expect it to produce a failure on `master`, and pass on this feature branch.  

I _think_ the problem is the creation of the test fixture.  

```
function makeTransactionWithHeaders (headers) {
  return {
    context: {
      request: {
        headers
      },
      response: {
        headers
      }
    }
  }
}
```

When we create the test fixture, we're using **same** instance object for the `request` and the `response` header.  This means when we filter this fixture and `request` gets filtered that the `response` object is also filtered -- because `response` and `request` both reference the same object.  This means it appears as though `response` has been filtered when, in the real world, `response` wouldn't be filtered because it was be a different object.

I'm guessing something like this would fix it

```
function makeTransactionWithHeaders (headersRequest, headersResponse) {
  return {
    context: {
      request: {
        headers:headersRequest
      },
      response: {
        headers:headersResponse
      }
    }
  }
}

//...

const headers = {
      'set-cookie': [
        'password=this-is-a-password',
        'card=1234%205678%201234%205678; Secure'
      ]
    }
const result = filters.process(
    makeTransactionWithHeaders(
        headers,
        Object.assign({}, headers) // clone the object
    )
  )
  
```

Do you think this is something we should fix before landing this?

**Comment by astorm** [comment]
jenkins run the tests please

**Comment by astorm** [comment]
@StoraH Hello!  We're about to begin work on [Align sanitize_field_names option + central config](https://github.com/elastic/apm-agent-nodejs/issues/1811), which is going to mean touching `lib/filters/http-headers.js`.  Because of that we'd like to get your work landed.  We'll merge the PR, and **_we'll take care_** of that one final nit with the test not working as  expected.  It's still worth your looking at though -- it's a nice lesson in how objects are passed around and referenced in javascript. 

Thanks again for finding and fixing this bug!

**Review by astorm — APPROVED** [review]
re approving from accidental close

**Comment by StoraH** [comment]
@astorm Hi! That's super good to hear! I'm glad this could move forward without me helping out at the last bit.
I've been home sick with covid and on top of that I replaced my computer with the new Macbook PRO with the M1 chip and sadly that can't run docker yet so weren't able to run the tests😅 I read thought the code again tho, and yes, that is a nice lesson :) I would say this whole experience have been a good lesson and I'm very glad how I was greeted into this community. I will gladly to more pull requests in the future🚀

All the best!

**Pull request merged**
