### PR TITLE
docs: fix broken links to APM docs

### PR DESCRIPTION
**Pull request by david-luna**
Some PRs cannot pass the docs generation check. The logs reveal som broken links
https://elasticsearch-ci.elastic.co/job/elastic+apm-agent-nodejs+pull-request+build-docs/2604/console

This PRs fix the broken links. Once passed there should be another similar PR for `3.x` branch

### Checklist

- [ ] Implement code
- [ ] Add tests
- [ ] Update TypeScript typings
- [x] Update documentation
- [ ] Add CHANGELOG.asciidoc entry
- [x] Commit message follows [commit guidelines](https://github.com/elastic/apm-agent-nodejs/blob/main/CONTRIBUTING.md#commit-message-guidelines)

### CODE REVIEW

**Comment by bmorelli25** [comment]
Thank you for this PR. Please hold off on merging this for now as I explore other fixes.

 I'm not sure yet if it makes more sense to fix these links in apm-server or in the agent repositories.

**Comment by david-luna** [comment]
> I'm not sure yet if it makes more sense to fix these links in apm-server or in the agent repositories.

This was a try to have a fix in this end. No problem in waiting

**Comment by bmorelli25** [comment]
We're safe to close this PR as fixes were published in the APM Server repo.

**Comment by trentm** [comment]
Politely re-opening this. While the current APM Server docs don't *404* for these links, they do either land on a less relevant page, or on a generic `This page has been deleted. Please see [What is APM?](https://www.elastic.co/guide/en/apm/guide/current/apm-overview.html).` page.

Also there is this unrelated change that restores using a basedir reference: https://github.com/elastic/apm-agent-nodejs/pull/3380/files#r1205545896

**Comment by trentm** [comment]
@bmorelli25 Are we safe to merge these changes?

**Review by trentm — APPROVED** [review]

**Comment by bmorelli25** [comment]
> Politely re-opening this. While the current APM Server docs don't 404 for these links, they do either land on a less relevant page, or on a generic This page has been deleted. Please see [What is APM?](https://www.elastic.co/guide/en/apm/guide/current/apm-overview.html). page.

I was hoping to fix these in APM Server instead of in the agent repos, but that plan failed (https://github.com/elastic/apm-server/pull/10917). Thanks for reopening and yes, we're good to merge this.

**Review by bmorelli25 — APPROVED** [review]

**Review by afharo — APPROVED** [review]
Approving to unblock (not sure why I'm a reviewer of this TBH 😅)

**Pull request merged**
